# Generated by Django 6.0.5 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="idempotency_key_hash",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="operation_fingerprint",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="sale",
            name="creation_response_snapshot",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="sold_by_principal_id",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="sold_by_principal_kind",
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("creation_response_snapshot__isnull", True),
                        ("idempotency_key_hash__isnull", True),
                        ("operation_fingerprint", ""),
                        ("sold_by_principal_id__isnull", True),
                        ("sold_by_principal_kind", ""),
                    ),
                    models.Q(
                        ("sold_by_principal_kind__in", ("staff", "teacher")),
                        ("sold_by_principal_id__isnull", False),
                        ("idempotency_key_hash__isnull", False),
                        models.Q(("operation_fingerprint", ""), _negated=True),
                        ("creation_response_snapshot__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sale_idempotency_shape",
            ),
        ),
    ]
