# Generated by Django 6.0.5 on 2026-06-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0002_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='primary_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cohorts', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cohorts.cohort'),
        ),
        migrations.AddField(
            model_name='cohortmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_memberships', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='cohortteacher',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teachers', to='cohorts.cohort'),
        ),
        migrations.AddField(
            model_name='cohortteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_teaching', to='teachers.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('branch', 'name')},
        ),
        migrations.AddConstraint(
            model_name='cohortmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('cohort', 'student'), name='one_active_membership_per_cohort_student'),
        ),
        migrations.AlterUniqueTogether(
            name='cohortteacher',
            unique_together={('cohort', 'teacher')},
        ),
    ]
