# Generated by Django 6.0.5 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


TYPE_DEFAULTS = {
    "main-teacher": ("Main Teacher", True, 10),
    "video-teacher": ("Video Teacher", False, 20),
    "assistant": ("Assistant", False, 30),
    "co-teacher": ("Co-teacher", False, 40),
}


def _ensure_types(apps):
    teacher_type = apps.get_model("teachers", "TeacherType")
    result = {}
    for slug, (name, is_default, sort_order) in TYPE_DEFAULTS.items():
        row, _ = teacher_type.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "description": "",
                "is_active": True,
                "is_system": True,
                "is_default": is_default,
                "sort_order": sort_order,
            },
        )
        result[slug] = row
    return result


def forwards(apps, schema_editor):
    cohort = apps.get_model("cohorts", "Cohort")
    assignment = apps.get_model("cohorts", "CohortTeacher")
    types = _ensure_types(apps)

    batch = []
    for row in assignment.objects.all().iterator(chunk_size=1000):
        slug = "assistant" if row.role == "assistant" else "co-teacher"
        row.teacher_type_id = types[slug].pk
        batch.append(row)
        if len(batch) == 1000:
            assignment.objects.bulk_update(batch, ["teacher_type"], batch_size=1000)
            batch.clear()
    if batch:
        assignment.objects.bulk_update(batch, ["teacher_type"], batch_size=1000)

    primary_rows = cohort.objects.exclude(primary_teacher_id__isnull=True).values_list(
        "id", "primary_teacher_id"
    )
    main_rows = (
        assignment(
            cohort_id=cohort_id,
            teacher_id=teacher_id,
            teacher_type_id=types["main-teacher"].pk,
        )
        for cohort_id, teacher_id in primary_rows.iterator(chunk_size=1000)
    )
    assignment.objects.bulk_create(main_rows, batch_size=1000)


def backwards(apps, schema_editor):
    assignment = apps.get_model("cohorts", "CohortTeacher")
    seen = set()
    for row in assignment.objects.select_related("teacher_type").order_by("pk"):
        key = (row.cohort_id, row.teacher_id)
        if key in seen:
            row.delete()
            continue
        seen.add(key)
        row.role = "assistant" if row.teacher_type.slug == "assistant" else "co_teacher"
        row.save(update_fields=["role"])


class Migration(migrations.Migration):
    # AddField defers its FK index until the schema editor exits. The data copy
    # below fires deferrable FK triggers, so PostgreSQL must be allowed to commit
    # those writes before Django emits the deferred CREATE INDEX.
    atomic = False

    dependencies = [
        ("cohorts", "0003_initial"),
        ("teachers", "0008_teachertype"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cohortteacher",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cohortteacher",
            name="teacher_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cohort_assignments",
                to="teachers.teachertype",
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
