# Generated by Django 6.0.5 on 2026-07-14

from django.db import migrations, models

CREATE_COMPATIBILITY_TRIGGER = r"""
CREATE OR REPLACE FUNCTION cohorts_sync_teacher_assignment_compat()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    map_from_role boolean := NEW.teacher_type_id IS NULL;
    mapped_type_id bigint;
    canonical_slug text;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        map_from_role := map_from_role OR (
            NEW.role IS DISTINCT FROM OLD.role
            AND NEW.teacher_type_id IS NOT DISTINCT FROM OLD.teacher_type_id
        );
    END IF;

    IF map_from_role THEN
        SELECT id INTO mapped_type_id
        FROM teachers_teachertype
        WHERE slug = CASE
            WHEN NEW.role = 'assistant' THEN 'assistant'
            ELSE 'co-teacher'
        END
        LIMIT 1;
        IF mapped_type_id IS NOT NULL THEN
            NEW.teacher_type_id := mapped_type_id;
        END IF;
    END IF;

    IF NEW.teacher_type_id IS NOT NULL THEN
        SELECT slug INTO canonical_slug
        FROM teachers_teachertype
        WHERE id = NEW.teacher_type_id;
        NEW.role := CASE
            WHEN canonical_slug = 'assistant' THEN 'assistant'
            ELSE 'co_teacher'
        END;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS cohorts_teacher_assignment_compat
ON cohorts_cohortteacher;
CREATE TRIGGER cohorts_teacher_assignment_compat
BEFORE INSERT OR UPDATE ON cohorts_cohortteacher
FOR EACH ROW
EXECUTE FUNCTION cohorts_sync_teacher_assignment_compat();
"""


DROP_COMPATIBILITY_TRIGGER = r"""
DROP TRIGGER IF EXISTS cohorts_teacher_assignment_compat
ON cohorts_cohortteacher;
DROP FUNCTION IF EXISTS cohorts_sync_teacher_assignment_compat();
"""


class Migration(migrations.Migration):
    """Finish the expand phase without breaking old nodes or rollback images.

    ``role`` and nullable ``teacher_type`` deliberately remain for this release.
    The trigger lets old nodes write their two-value role while new nodes use the
    typed FK, and keeps both representations synchronized. A later contract
    release may enforce NOT NULL and remove ``role`` after old images are retired.
    """

    dependencies = [
        ("cohorts", "0004_typed_teacher_assignments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cohortteacher",
            options={"ordering": ("cohort", "teacher_type", "teacher")},
        ),
        migrations.AddConstraint(
            model_name="cohortteacher",
            constraint=models.UniqueConstraint(
                fields=("cohort", "teacher", "teacher_type"),
                name="unique_cohort_teacher_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortteacher",
            constraint=models.UniqueConstraint(
                condition=models.Q(teacher_type__isnull=True),
                fields=("cohort", "teacher"),
                name="unique_legacy_untyped_cohort_teacher",
            ),
        ),
        migrations.RunSQL(
            sql=CREATE_COMPATIBILITY_TRIGGER,
            reverse_sql=DROP_COMPATIBILITY_TRIGGER,
        ),
    ]
