# Generated by Django 6.0 on 2026-08-20.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleImportDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("student", "Students"), ("teacher", "Teachers")], db_index=True, max_length=16)),
                ("source_file_name", models.CharField(max_length=255)),
                ("source_sheet", models.CharField(blank=True, max_length=255)),
                ("principal_kind", models.CharField(max_length=16)),
                ("principal_id", models.PositiveBigIntegerField()),
                ("default_branch_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("queued", "Queued"), ("processing", "Processing"), ("needs_attention", "Needs attention"), ("completed", "Completed"), ("failed", "Failed")], db_index=True, default="draft", max_length=24)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("ready_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("excluded_count", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="people_import_drafts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["kind", "status", "-updated_at"], name="people_import_kind_state_idx"),
                    models.Index(fields=["created_by", "principal_kind", "principal_id", "-updated_at"], name="people_import_owner_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PeopleImportRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("source_data", models.JSONField(default=dict)),
                ("data", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=dict)),
                ("state", models.CharField(choices=[("ready", "Ready"), ("invalid", "Needs attention"), ("imported", "Imported")], db_index=True, default="ready", max_length=16)),
                ("is_included", models.BooleanField(db_index=True, default=True)),
                ("created_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("draft", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="people_imports.peopleimportdraft")),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [models.Index(fields=["draft", "state", "is_included", "position"], name="people_import_row_state_idx")],
                "constraints": [models.UniqueConstraint(fields=("draft", "position"), name="people_import_unique_row")],
            },
        ),
    ]

