# Generated by Django 6.0.5 on 2026-06-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at', 'id')},
        ),
    ]
