# Generated by Django 6.0.7 on 2026-08-13 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0008_threadparticipant_archive_and_hide"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reactor_principal_kind",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("staff", "Staff"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("reactor_principal_id", models.PositiveBigIntegerField(editable=False)),
                ("emoji", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="MessageRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(choices=[("edited", "Edited"), ("deleted", "Deleted")], max_length=12),
                ),
                (
                    "actor_principal_kind",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("staff", "Staff"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("actor_principal_id", models.PositiveBigIntegerField(editable=False)),
                ("previous_body", models.TextField()),
                ("previous_edited_at", models.DateTimeField(blank=True, null=True)),
                ("previous_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("message_id", "version"),
            },
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="threadrealtimeevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("message.created", "Message created"),
                    ("message.updated", "Message updated"),
                    ("message.deleted", "Message deleted"),
                    ("reaction.added", "Reaction added"),
                    ("reaction.removed", "Reaction removed"),
                    ("read.updated", "Read state updated"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)), name="messaging_message_version_positive"
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="messaging.message"
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="reactor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagerevision",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagerevision",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="messaging.message"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereaction",
            index=models.Index(fields=["message", "removed_at", "emoji"], name="msg_reaction_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("message", "reactor_principal_kind", "reactor_principal_id", "emoji"),
                name="one_active_message_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reactor_principal_kind__in", ["student", "teacher", "parent", "staff"]),
                    ("reactor_principal_id__gt", 0),
                ),
                name="messaging_reaction_actor_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagerevision",
            constraint=models.UniqueConstraint(
                fields=("message", "version"), name="one_messaging_revision_per_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version__gt", 1),
                    ("actor_principal_kind__in", ["student", "teacher", "parent", "staff"]),
                    ("actor_principal_id__gt", 0),
                ),
                name="messaging_revision_shape",
            ),
        ),
    ]
