# Generated by Django 6.0.5 on 2026-06-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0003_initial'),
        ('org', '0009_centersettings_default_language'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(blank=True, max_length=32)),
                ('scope', models.CharField(choices=[('group', 'Group'), ('global', 'Global')], max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending approval'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=8)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='org.branch')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AchievementGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='achievements.achievement')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_grants', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-granted_at',),
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['scope', 'status'], name='achievement_scope_fb4209_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementgrant',
            index=models.Index(fields=['student', 'granted_at'], name='achievement_student_5eda0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='achievementgrant',
            constraint=models.UniqueConstraint(fields=('achievement', 'student'), name='one_grant_per_achievement_per_student'),
        ),
    ]
