# Generated by Django 6.0.5 on 2026-06-27 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_initial'),
        ('placement', '0003_groupproposal'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('student', 'cohort'), name='one_pending_proposal_per_student_cohort'),
        ),
    ]
