# Generated by Django 6.0.5 on 2026-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_groupproposal_one_pending_proposal_per_student_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementtest',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
