# Generated by Django 6.0.5 on 2026-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_placementattempt_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice (multi-select)'), ('true_false', 'True / false'), ('writing', 'Writing (manually marked)')], max_length=16),
        ),
    ]
