# Generated by Django 6.0.5 on 2026-06-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_alter_placementquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice (multi-select)'), ('short_answer', 'Short answer (typed, auto-graded)'), ('true_false', 'True / false'), ('writing', 'Writing (manually marked)')], max_length=16),
        ),
    ]
