# Generated by Django 6.0.5 on 2026-07-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_alter_placementquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementquestion',
            name='media',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice (multi-select)'), ('short_answer', 'Short answer (typed, auto-graded)'), ('true_false', 'True / false'), ('writing', 'Writing (manually marked)'), ('reading', 'Reading (manually marked)'), ('listening', 'Listening (audio prompt, manually marked)'), ('speaking', 'Speaking (audio answer, manually marked)')], max_length=16),
        ),
    ]
