# Generated by Django 6.0.5 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_campaign_scheduled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="last_error",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_claim_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status", "scheduled_at"], name="campaign_due_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["status", "send_heartbeat_at"], name="campaign_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignrecipient",
            index=models.Index(
                fields=["campaign", "status", "id"],
                name="campaign_recipient_work_idx",
            ),
        ),
    ]
