# Generated by Django 6.0.5 on 2026-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesnapshot',
            name='dau',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
