# Generated by Django 6.0.5 on 2026-06-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usagesnapshot_dau'),
        ('tenancy', '0003_platformevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsageCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the billing month this charge covers.')),
                ('included_tokens', models.BigIntegerField(default=0)),
                ('used_tokens', models.BigIntegerField(default=0)),
                ('overage_tokens', models.BigIntegerField(default=0)),
                ('rate_per_1k_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cost_microusd', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-period', 'center_id'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_overage_price_per_1k_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('ai_overage_price_per_1k_uzs__gte', 0)), name='plan_ai_overage_price_non_negative'),
        ),
        migrations.AddField(
            model_name='aiusagecharge',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_charges', to='tenancy.center'),
        ),
        migrations.AddConstraint(
            model_name='aiusagecharge',
            constraint=models.UniqueConstraint(fields=('center', 'period'), name='ai_charge_one_per_center_period'),
        ),
        migrations.AddConstraint(
            model_name='aiusagecharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_uzs__gte', 0)), name='ai_charge_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='aiusagecharge',
            constraint=models.CheckConstraint(condition=models.Q(('overage_tokens__gte', 0)), name='ai_charge_overage_non_negative'),
        ),
    ]
