# Generated by Django 6.0.5 on 2026-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentmethod_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='single_use',
            field=models.BooleanField(default=False),
        ),
    ]
