# Generated by Django 6.0.5 on 2026-06-12 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('cohorts', '0003_initial'),
        ('org', '0004_centersettings_academic_warning_max_and_more'),
        ('schedule', '0002_lesson_recurrencerule_term_timeslot_and_more'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('project', 'Project'), ('oral', 'Oral')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='schedule.term')),
            ],
            options={
                'ordering': ('-exam_date',),
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.exam')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='students.studentprofile')),
            ],
            options={
                'ordering': ('-graded_at',),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_raw', models.DecimalField(decimal_places=3, max_digits=6)),
                ('value_display', models.CharField(max_length=8)),
                ('components', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='students.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='schedule.term')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='org.department')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('pdf_key', models.CharField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='students.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='schedule.term')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='AcademicItem',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.subject'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='examresult_unique_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='examresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='examresult_score_nonneg'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'term'], name='academics_g_student_846a4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'term'), name='grade_unique_student_subject_term'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['cohort', 'term'], name='academics_e_cohort__dc21eb_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'term'], name='academics_e_subject_b26858_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='exam_max_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='exam_weight_positive'),
        ),
    ]
