# Generated by Django 6.0.5 on 2026-07-09 19:40
import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

# The five kinds the old Exam.Type enum shipped with — seeded per tenant so every
# center starts with sensible defaults it can then rename / extend / deactivate.
_DEFAULTS = [
    ("midterm", "Midterm"),
    ("final", "Final"),
    ("quiz", "Quiz"),
    ("project", "Project"),
    ("oral", "Oral"),
]


def seed_and_map(apps, schema_editor):
    """Seed the default ExamType rows and point every existing exam at the row
    matching its old `type` slug. Runs once per tenant schema."""
    ExamType = apps.get_model("academics", "ExamType")
    Exam = apps.get_model("academics", "Exam")
    by_slug = {}
    for slug, name in _DEFAULTS:
        obj, _ = ExamType.objects.get_or_create(slug=slug, defaults={"name": name})
        by_slug[slug] = obj
    for exam in Exam.objects.all().only("id", "type"):
        et = by_slug.get(exam.type)
        if et is None and exam.type:
            # A non-default legacy value — materialize it as its own type so nothing is lost.
            et, _ = ExamType.objects.get_or_create(
                slug=slugify(exam.type)[:64] or exam.type[:64],
                defaults={"name": exam.type[:64]},
            )
        if et is not None:
            Exam.objects.filter(pk=exam.pk).update(exam_type=et)


def unmap(apps, schema_editor):
    """Reverse: restore the legacy `type` slug where it still fits the old
    varchar(10) enum column. A center-authored type with a longer slug has no
    legacy enum equivalent, so leave `type` blank rather than overflow the column
    (writing a >10-char slug into varchar(10) would raise DataError and abort the
    rollback for that tenant)."""
    Exam = apps.get_model("academics", "Exam")
    for exam in Exam.objects.select_related("exam_type").all():
        slug = exam.exam_type.slug if exam.exam_type_id else ""
        Exam.objects.filter(pk=exam.pk).update(type=slug if len(slug) <= 10 else "")


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_exam_examresult_grade_subject_transcript_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        # Add the FK nullable first so we can map data into it before dropping `type`.
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.examtype'),
        ),
        migrations.RunPython(seed_and_map, unmap),
        migrations.RemoveField(
            model_name='exam',
            name='type',
        ),
    ]
