from django.urls import path

from apps.payroll.views.v1.payroll_views import (
    adjustment_approve_view,
    adjustment_detail_view,
    adjustment_events_view,
    adjustment_reject_view,
    adjustments_view,
    disbursements_view,
    payslip_detail_view,
    payslip_mine_detail_view,
    payslips_mine_view,
    period_approve_view,
    period_detail_view,
    period_events_view,
    period_export_detail_view,
    period_exports_view,
    period_lines_view,
    period_preview_view,
    period_reconcile_view,
    period_reconciliations_view,
    period_reject_view,
    period_run_view,
    period_totals_view,
    periods_view,
    reconciliation_detail_view,
    reconciliation_reverse_view,
)

urlpatterns = [
    path("disbursements/", disbursements_view, name="payroll-disbursements"),
    path("periods/", periods_view, name="payroll-periods"),
    path("periods/<int:pk>/", period_detail_view, name="payroll-period-detail"),
    path("periods/<int:pk>/preview/", period_preview_view, name="payroll-period-preview"),
    path("periods/<int:pk>/run/", period_run_view, name="payroll-period-run"),
    path("periods/<int:pk>/approve/", period_approve_view, name="payroll-period-approve"),
    path("periods/<int:pk>/reject/", period_reject_view, name="payroll-period-reject"),
    path("periods/<int:pk>/lines/", period_lines_view, name="payroll-period-lines"),
    path("periods/<int:pk>/events/", period_events_view, name="payroll-period-events"),
    path("periods/<int:pk>/totals/", period_totals_view, name="payroll-period-totals"),
    path("periods/<int:pk>/reconcile/", period_reconcile_view, name="payroll-period-reconcile"),
    path(
        "periods/<int:pk>/reconciliations/",
        period_reconciliations_view,
        name="payroll-period-reconciliations",
    ),
    path("periods/<int:pk>/exports/", period_exports_view, name="payroll-period-exports"),
    path(
        "periods/<int:pk>/exports/<int:export_id>/",
        period_export_detail_view,
        name="payroll-period-export-detail",
    ),
    path("adjustments/", adjustments_view, name="payroll-adjustments"),
    path("adjustments/<int:pk>/", adjustment_detail_view, name="payroll-adjustment-detail"),
    path(
        "adjustments/<int:pk>/events/",
        adjustment_events_view,
        name="payroll-adjustment-events",
    ),
    path(
        "adjustments/<int:pk>/approve/",
        adjustment_approve_view,
        name="payroll-adjustment-approve",
    ),
    path(
        "adjustments/<int:pk>/reject/",
        adjustment_reject_view,
        name="payroll-adjustment-reject",
    ),
    path("payslips/mine/", payslips_mine_view, name="payroll-payslips-mine"),
    path("payslips/mine/<int:pk>/", payslip_mine_detail_view, name="payroll-payslip-mine-detail"),
    path("payslips/<int:pk>/", payslip_detail_view, name="payroll-payslip-detail"),
    path(
        "reconciliations/<int:pk>/",
        reconciliation_detail_view,
        name="payroll-reconciliation-detail",
    ),
    path(
        "reconciliations/<int:pk>/reverse/",
        reconciliation_reverse_view,
        name="payroll-reconciliation-reverse",
    ),
]
