# Generated by Django 6.0.5 on 2026-06-12 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_exam_examresult_grade_subject_transcript_and_more'),
        ('cohorts', '0003_initial'),
        ('content', '0001_initial'),
        ('org', '0006_centersettings_storage_quota_gb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('module', 'order'),
            },
        ),
        migrations.CreateModel(
            name='ContentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('tenant', 'Everyone in the center'), ('department', 'A department'), ('cohort', 'A cohort'), ('role', 'Specific roles')], default='tenant', max_length=12)),
                ('allowed_roles', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='cohorts.cohort')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='org.department')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.contentlibrary')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.subject')),
            ],
            options={
                'ordering': ('library', 'order'),
            },
        ),
        migrations.CreateModel(
            name='FileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='content.contentlibrary')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.folder')),
            ],
            options={
                'ordering': ('library', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.folder')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.contentlesson')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='content.lessonfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course')),
            ],
            options={
                'ordering': ('course', 'order'),
            },
        ),
        migrations.DeleteModel(
            name='ContentItem',
        ),
        migrations.AddField(
            model_name='fileview',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='content.lessonfile'),
        ),
        migrations.AddField(
            model_name='contentlesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('library', 'parent', 'name'), name='folder_unique_path'),
        ),
        migrations.AddIndex(
            model_name='lessonfile',
            index=models.Index(fields=['status'], name='content_les_status_1813c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonfile',
            index=models.Index(fields=['folder'], name='content_les_folder__410b04_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonfile',
            index=models.Index(fields=['lesson'], name='content_les_lesson__850383_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonfile',
            constraint=models.CheckConstraint(condition=models.Q(('lesson__isnull', False), ('folder__isnull', False), _connector='OR'), name='lessonfile_lesson_or_folder'),
        ),
        migrations.AddIndex(
            model_name='fileview',
            index=models.Index(fields=['file', 'created_at'], name='content_fil_file_id_3d2139_idx'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='module_unique_course_order'),
        ),
    ]
