# Generated by Django 6.0.5 on 2026-06-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentlesson_contentlibrary_course_fileview_folder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfile',
            name='approved_manager_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='approved_manager_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='approved_teacher_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='approved_teacher_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='is_approved_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='is_approved_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonfile',
            name='is_downloadable',
            field=models.BooleanField(default=True),
        ),
    ]
