# Generated by Django 6.0.5 on 2026-06-11 21:49

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason_code', models.CharField(blank=True, choices=[('completed', 'Completed'), ('moved_city', 'Moved city'), ('financial', 'Financial'), ('behavior', 'Behavior'), ('schedule_conflict', 'Schedule conflict'), ('other', 'Other')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('application', 'Application'), ('accepted', 'Accepted'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], db_index=True, default='lead', max_length=16)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('academic_level', models.CharField(blank=True, max_length=64)),
                ('medical_notes', core.fields.EncryptedTextField(blank=True)),
                ('emergency_contacts', models.JSONField(blank=True, default=list)),
                ('photo', models.ImageField(blank=True, upload_to='students/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
