# Generated by Django 6.0.5 on 2026-07-09 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_initial'),
        ('org', '0014_centersettings_absence_deduction_enabled_and_more'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['-created_at', 'id'], name='student_created_idx'),
        ),
    ]
