# Generated by Django 6.0.5 on 2026-07-09 20:22

from django.db import migrations, models

# The reasons the old EnrollmentEvent.ReasonCode enum shipped with — seeded per
# tenant as EnrollmentReason rows so every center starts with sensible defaults it
# can then rename / extend / deactivate. Existing events already store these slugs,
# so no data mapping is needed (reason_code stays a denormalized slug).
_DEFAULTS = [
    ("completed", "Completed"),
    ("moved_city", "Moved city"),
    ("financial", "Financial"),
    ("behavior", "Behavior"),
    ("schedule_conflict", "Schedule conflict"),
    ("other", "Other"),
]


def seed_defaults(apps, schema_editor):
    EnrollmentReason = apps.get_model("students", "EnrollmentReason")
    for slug, name in _DEFAULTS:
        EnrollmentReason.objects.get_or_create(slug=slug, defaults={"name": name})


def unseed(apps, schema_editor):
    EnrollmentReason = apps.get_model("students", "EnrollmentReason")
    EnrollmentReason.objects.filter(slug__in=[slug for slug, _ in _DEFAULTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_student_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='enrollmentevent',
            name='reason_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(seed_defaults, unseed),
    ]
