# Generated by Django 6.0.5 on 2026-07-10 11:29

from django.db import migrations, models


def backfill_identity_from_user(apps, schema_editor):
    """Copy each existing student's identity off their User onto the StudentProfile,
    which now owns it (role-native-auth migration). Runs once per tenant schema."""
    StudentProfile = apps.get_model("students", "StudentProfile")
    for sp in StudentProfile.objects.select_related("user").iterator():
        u = sp.user
        StudentProfile.objects.filter(pk=sp.pk).update(
            first_name=u.first_name or "",
            last_name=u.last_name or "",
            middle_name=u.middle_name or "",
            phone=u.phone or "",
            email=u.email or "",
            birthdate=u.birthdate,
            gender=u.gender or "",
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_enrollmentreason_alter_enrollmentevent_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=8),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.RunPython(backfill_identity_from_user, noop),
    ]
