# Generated by Django 6.0.5 on 2026-07-13 15:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cohorts", "0003_initial"),
        ("org", "0018_staffprofile_staff_phone_unique_nonblank_and_more"),
        ("students", "0008_alter_studentprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("phone",),
                name="student_phone_unique_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="student_email_unique_nonblank_ci",
            ),
        ),
    ]
