# Generated by Django 6.0.5 on 2026-07-09 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_centersettings_absence_deduction_enabled_and_more'),
        ('printing', '0002_printer_branchagent_printjob_delete_printingitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['-created_at', 'id'], name='printjob_created_idx'),
        ),
    ]
