"""Service port for the finance app."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from django.db.models import QuerySet

from apps.finance.models import (
    CashierShift,
    Discount,
    Expense,
    FeeSchedule,
    Invoice,
    PaymentMethod,
    PaymentPlan,
)


class IFinanceService(ABC):
    # --- fee schedules (CRUD) ---
    @abstractmethod
    def fee_schedules(self) -> QuerySet[FeeSchedule]: ...
    @abstractmethod
    def fee_schedule(self, pk: int) -> FeeSchedule | None: ...
    @abstractmethod
    def create_fee_schedule(self, *, data: dict[str, Any]) -> FeeSchedule: ...
    @abstractmethod
    def update_fee_schedule(self, *, fee_schedule: FeeSchedule, changes: dict[str, Any]) -> FeeSchedule: ...
    @abstractmethod
    def delete_fee_schedule(self, *, fee_schedule: FeeSchedule) -> None: ...

    # --- invoices ---
    @abstractmethod
    def invoices(self, *, user, roles: set[str]) -> QuerySet[Invoice]: ...
    @abstractmethod
    def invoice(self, *, pk: int, user, roles: set[str]) -> Invoice | None: ...
    @abstractmethod
    def issue_invoice(self, *, student_id: int, fee_schedule_id, lines, period: str, created_by) -> Invoice: ...
    @abstractmethod
    def void_invoice(self, *, invoice: Invoice, actor) -> Invoice: ...
    @abstractmethod
    def reload_invoice(self, *, pk: int, user, roles: set[str]) -> Invoice | None: ...
    @abstractmethod
    def create_payment_plan(self, *, invoice: Invoice, installments: list[dict], created_by) -> PaymentPlan: ...

    # --- discounts ---
    @abstractmethod
    def discounts(self) -> QuerySet[Discount]: ...
    @abstractmethod
    def discount(self, pk: int) -> Discount | None: ...
    @abstractmethod
    def deactivate_discount(self, *, discount: Discount) -> Discount: ...

    # --- payment methods (CRUD) ---
    @abstractmethod
    def payment_methods(self) -> QuerySet[PaymentMethod]: ...
    @abstractmethod
    def payment_method(self, pk: int) -> PaymentMethod | None: ...
    @abstractmethod
    def create_payment_method(self, *, data: dict[str, Any]) -> PaymentMethod: ...
    @abstractmethod
    def update_payment_method(self, *, payment_method: PaymentMethod, changes: dict[str, Any]) -> PaymentMethod: ...
    @abstractmethod
    def delete_payment_method(self, *, payment_method: PaymentMethod) -> None: ...

    # --- expenses ---
    @abstractmethod
    def expenses(self) -> QuerySet[Expense]: ...
    @abstractmethod
    def expense(self, pk: int) -> Expense | None: ...
    @abstractmethod
    def create_expense(self, *, branch, description: str, amount_uzs, category: str, created_by) -> Expense: ...
    @abstractmethod
    def approve_expense(self, *, expense_id: int, actor) -> Expense: ...
    @abstractmethod
    def reject_expense(self, *, expense_id: int, reason: str, actor) -> Expense: ...
    @abstractmethod
    def pay_expense(self, *, expense_id: int, payment_method_id: int, actor) -> Expense: ...

    # --- cashier shifts ---
    @abstractmethod
    def cashier_shifts(self) -> QuerySet[CashierShift]: ...
    @abstractmethod
    def cashier_shift(self, pk: int) -> CashierShift | None: ...
    @abstractmethod
    def open_cashier_shift(self, *, cashier, branch, opening_cash_uzs, notes: str) -> CashierShift: ...
    @abstractmethod
    def close_cashier_shift(self, *, shift: CashierShift, closing_cash_uzs, notes: str) -> CashierShift: ...
    @abstractmethod
    def cashier_shift_report(self, *, shift: CashierShift) -> dict: ...

    # --- outstanding balance ---
    @abstractmethod
    def outstanding(self, *, student_id: int, user, roles: set[str]) -> tuple[Any, QuerySet[Invoice]]: ...
    @abstractmethod
    def parent_can_see_student(self, *, user, student_id: int) -> bool: ...
