# Generated by Django 6.0.5 on 2026-06-11 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardian',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='parents.parentprofile'),
        ),
        migrations.AddField(
            model_name='pickupauthorization',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_authorizations', to='students.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='one_primary_guardian_per_student'),
        ),
        migrations.AlterUniqueTogether(
            name='guardian',
            unique_together={('parent', 'student')},
        ),
    ]
