# Generated by Django 6.0.5 on 2026-07-10 12:11

import django.contrib.auth.validators
from django.db import migrations, models



def backfill_credentials_from_user(apps, schema_editor):
    """Carry each parent's login credentials over from their User onto the parent account
    (role-native auth): same username + password hash, so when role-native login goes live
    they sign in unchanged. Runs per tenant schema."""
    Profile = apps.get_model("parents", "ParentProfile")
    for row in Profile.objects.select_related("user").iterator():
        u = row.user
        Profile.objects.filter(pk=row.pk).update(
            username=u.username,
            password=u.password,
            is_active=u.is_active,
            last_login_at=u.last_login,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0004_parent_owns_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='username',
            field=models.CharField(blank=True, help_text='Login identifier for this role account.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.RunPython(backfill_credentials_from_user, noop),
    ]
