# Generated by Django 6.0.5 on 2026-06-26 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0001_initial'),
        ('org', '0009_centersettings_default_language'),
        ('schedule', '0003_lessontype_lesson_lesson_type_and_more'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coverrequest',
            name='one_live_cover_per_lesson',
        ),
        migrations.AddConstraint(
            model_name='coverrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('lesson',), name='one_live_cover_per_lesson'),
        ),
    ]
