# Generated by Django 6.0.5 on 2026-06-26 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('org', '0009_centersettings_default_language'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waived', 'Waived')], db_index=True, default='active', max_length=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waive_reason', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='org.branch')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='compliance.rule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='students.studentprofile')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['student', 'status'], name='compliance__student_e36df4_idx'), models.Index(fields=['branch', 'status'], name='compliance__branch__60f851_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='penalty_points_positive')],
            },
        ),
    ]
