# Generated by Django 6.0.5 on 2026-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
    ]
