# Generated by Django 6.0.5 on 2026-06-28 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_penalty_escalated'),
        ('org', '0013_centersettings_show_classroom_rank'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='students.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='penalty',
            index=models.Index(fields=['staff', 'status'], name='compliance__staff_i_ec5ca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='penalty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='penalty_exactly_one_subject'),
        ),
    ]
