"""Notification endpoints — plain Django views over the layered architecture.

The in-app feed + read receipts are ALWAYS own-row only (any authenticated user may
read/manage their OWN feed — gating at a role code would lock ordinary users out of
notifications they receive). Preferences are own-row (notifications:read). Templates are
admin config (notifications:write — director/IT only). Announcements fan out to a cohort
(notifications:write + a per-(schema,user) rate cap). Notifications are server-generated;
clients never POST them.
"""

from __future__ import annotations

from typing import Any

from django.http import HttpRequest, HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt

from apps.notifications.dto.notification_dto import (
    AnnouncementDTO,
    CreateTemplateDTO,
    PreferenceRowDTO,
)
from apps.notifications.interfaces.services import INotificationService, INotificationTemplateService
from apps.notifications.models import Channel, EventType, Locale
from apps.notifications.presenters import notification_to_dict, preference_to_dict, template_to_dict
from core.api_auth import check_perm, deny_read_only_token, require_auth
from core.container import container
from core.exceptions import NotFoundException, PermissionException, ValidationException
from core.http import bool_field, int_field, read_json, str_field
from core.listing import apply_filters, cursor_paginate, paginate
from core.ratelimit import check_rate
from core.responses import created, error, no_content, paginated, success
from core.scoping import branch_ids, is_unscoped
from core.utils import current_schema

_RESOURCE = "notifications"
_EVENT_TYPES = {value for value, _label in EventType.choices}
_CHANNELS = {value for value, _label in Channel.choices}
_LOCALES = {value for value, _label in Locale.choices}


def _service() -> INotificationService:
    return container.resolve(INotificationService)  # type: ignore[type-abstract]


def _template_service() -> INotificationTemplateService:
    return container.resolve(INotificationTemplateService)  # type: ignore[type-abstract]


# --- feed + read receipts (own rows; any authenticated user) ---------------
@csrf_exempt
@require_auth
def notifications_collection_view(request: HttpRequest) -> HttpResponse:
    if request.method in ("GET", "HEAD"):
        # Preserve the old feed filters (filterset_fields=("event_type","read_at")); the
        # cursor paginator owns the ordering, so pass no ordering_fields and keep the
        # queryset ordered (-created_at,-id).
        qs = apply_filters(
            request, _service().feed(user=request.user), filter_fields=("event_type", "read_at")
        )
        rows, next_link, previous_link = cursor_paginate(request, qs)
        return JsonResponse(
            {
                "results": [notification_to_dict(n) for n in rows],
                "next": next_link,
                "previous": previous_link,
            }
        )
    if request.method == "POST":
        # Notifications are server-generated; clients never POST them directly.
        return error("Notifications are generated by the system.", code="method_not_allowed", status=405)
    return error("Method not allowed.", code="method_not_allowed", status=405)


@csrf_exempt
@require_auth
def notification_unread_count_view(request: HttpRequest) -> HttpResponse:
    if request.method not in ("GET", "HEAD"):
        return error("Method not allowed.", code="method_not_allowed", status=405)
    return success({"count": _service().unread_count(user=request.user)})


@csrf_exempt
@require_auth
def notification_read_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method != "POST":
        return error("Method not allowed.", code="method_not_allowed", status=405)
    deny_read_only_token(request)  # a read-only impersonation token may not mutate
    notification = _service().get_own(user=request.user, pk=pk)
    if notification is None:  # someone else's pk -> 404 (own-rows read scoping)
        raise NotFoundException(code="not_found")
    _service().mark_read(user=request.user, notification_id=notification.pk)
    return success({"read": True})


@csrf_exempt
@require_auth
def notification_read_all_view(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return error("Method not allowed.", code="method_not_allowed", status=405)
    deny_read_only_token(request)
    return success({"updated": _service().mark_all_read(user=request.user)})


# --- preferences (own rows; notifications:read) ----------------------------
@csrf_exempt
@require_auth
def preferences_view(request: HttpRequest) -> HttpResponse:
    if request.method in ("GET", "HEAD"):
        check_perm(request, f"{_RESOURCE}:read")
        prefs = _service().preferences(user=request.user)
        return success([preference_to_dict(p) for p in prefs])
    if request.method == "PUT":
        check_perm(request, f"{_RESOURCE}:read")  # non-SAFE -> also denies a read-only token
        updated = _service().upsert_preferences(user=request.user, rows=_pref_rows(read_json(request)))
        return success([preference_to_dict(p) for p in updated])
    return error("Method not allowed.", code="method_not_allowed", status=405)


# --- templates (admin config; notifications:write) -------------------------
@csrf_exempt
@require_auth
def templates_collection_view(request: HttpRequest) -> HttpResponse:
    if request.method in ("GET", "HEAD"):
        check_perm(request, f"{_RESOURCE}:write")
        qs = apply_filters(
            request,
            _template_service().list(),
            filter_fields=("event_type", "channel", "locale", "is_active"),
            ordering_fields=("event_type", "channel", "locale"),
        )
        items, total, page, size = paginate(request, qs)
        return paginated([template_to_dict(t) for t in items], total=total, page=page, page_size=size)
    if request.method == "POST":
        check_perm(request, f"{_RESOURCE}:write")
        template = _template_service().create(_template_dto(read_json(request)))
        return created(template_to_dict(template))
    return error("Method not allowed.", code="method_not_allowed", status=405)


@csrf_exempt
@require_auth
def template_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    read = request.method in ("GET", "HEAD")
    check_perm(request, f"{_RESOURCE}:write")  # reads are gated at :write too (admin only)
    template = _template_service().get(pk=pk)
    if template is None:
        raise NotFoundException(code="not_found")
    if read:
        return success(template_to_dict(template))
    if request.method in ("PUT", "PATCH"):
        result = _template_service().update(template, _template_changes(read_json(request)))
        return success(template_to_dict(result))
    if request.method == "DELETE":
        _template_service().delete(template)
        return no_content()
    return error("Method not allowed.", code="method_not_allowed", status=405)


# --- announcements (notifications:write + rate cap) ------------------------
@csrf_exempt
@require_auth
def announcement_view(request: HttpRequest) -> HttpResponse:
    if request.method != "POST":
        return error("Method not allowed.", code="method_not_allowed", status=405)
    check_perm(request, f"{_RESOURCE}:write")
    actor: Any = request.user
    dto = _announcement_dto(read_json(request))
    # Object-level scope: an announcement fans out to every member of the target cohort, so a
    # branch-scoped writer (if a center A-2-grants notifications:write to one, e.g. a registrar)
    # must not blast ANOTHER branch's cohort. Mirrors the achievements/cards/sales student-write
    # guards; a no-op for a director/superuser. A non-existent cohort resolves the same 403 as a
    # foreign one, so it is not a cohort-existence oracle across the branch boundary.
    if not is_unscoped(request):
        from apps.cohorts.models import Cohort

        cohort_branch_id = Cohort.objects.filter(pk=dto.cohort_id).values_list("branch_id", flat=True).first()
        if cohort_branch_id is None or cohort_branch_id not in branch_ids(request):
            raise PermissionException(
                "You can only announce to a cohort in your own branch.", code="branch_out_of_scope"
            )
    # Mass messaging is expensive (per-recipient fan-out); cap per (schema, user).
    check_rate(scope="announcement", key=f"{current_schema()}:{actor.pk}", limit=10, window=60)
    result = _service().announce(dto, actor=request.user)
    return success(result, status=202)


# --- helpers ---------------------------------------------------------------
def _choice(body: dict[str, Any], name: str, valid: set[str]) -> str:
    value = str_field(body, name, max_length=64)
    if value not in valid:
        raise ValidationException(
            f"{name} is not a valid choice.",
            code="validation_error",
            fields={name: [f"Must be one of: {sorted(valid)}."]},
        )
    return value


def _pref_rows(body: dict[str, Any]) -> list[PreferenceRowDTO]:
    raw = body.get("preferences")
    if not isinstance(raw, list):
        raise ValidationException(
            "preferences must be a list.",
            code="validation_error",
            fields={"preferences": ["Provide a list of {event_type, channel, enabled}."]},
        )
    rows: list[PreferenceRowDTO] = []
    for index, item in enumerate(raw):
        if not isinstance(item, dict):
            raise ValidationException(
                f"Preference {index} must be an object.",
                code="validation_error",
                fields={"preferences": [f"Item {index} must be an object."]},
            )
        rows.append(
            PreferenceRowDTO(
                event_type=_choice(item, "event_type", _EVENT_TYPES),
                channel=_choice(item, "channel", _CHANNELS),
                enabled=bool_field(item, "enabled", default=True),
            )
        )
    return rows


def _template_dto(body: dict[str, Any]) -> CreateTemplateDTO:
    template_body = str_field(body, "body").strip()  # DRF TextField trims whitespace
    if not template_body:  # model body is a required TextField
        raise ValidationException(
            "body is required.", code="validation_error", fields={"body": ["This field is required."]}
        )
    return CreateTemplateDTO(
        event_type=_choice(body, "event_type", _EVENT_TYPES),
        channel=_choice(body, "channel", _CHANNELS),
        locale=_choice(body, "locale", _LOCALES),
        body=template_body,
        subject=str_field(body, "subject", max_length=255),
        is_active=bool_field(body, "is_active", default=True),
    )


def _template_changes(body: dict[str, Any]) -> dict[str, Any]:
    changes: dict[str, Any] = {}
    if "event_type" in body:
        changes["event_type"] = _choice(body, "event_type", _EVENT_TYPES)
    if "channel" in body:
        changes["channel"] = _choice(body, "channel", _CHANNELS)
    if "locale" in body:
        changes["locale"] = _choice(body, "locale", _LOCALES)
    if "subject" in body:
        changes["subject"] = str_field(body, "subject", max_length=255)
    if "body" in body:
        template_body = str_field(body, "body").strip()
        if not template_body:
            raise ValidationException(
                "body may not be blank.", code="validation_error", fields={"body": ["May not be blank."]}
            )
        changes["body"] = template_body
    if "is_active" in body:
        changes["is_active"] = bool_field(body, "is_active")
    return changes


def _announcement_dto(body: dict[str, Any]) -> AnnouncementDTO:
    cohort_id = int_field(body, "cohort", required=True)
    title = str_field(body, "title", max_length=255).strip()  # DRF CharField trims whitespace
    if not title:
        raise ValidationException(
            "title is required.", code="validation_error", fields={"title": ["This field is required."]}
        )
    announcement_body = str_field(body, "body").strip()
    if not announcement_body:
        raise ValidationException(
            "body is required.", code="validation_error", fields={"body": ["This field is required."]}
        )
    return AnnouncementDTO(cohort_id=cohort_id, title=title, body=announcement_body)  # type: ignore[arg-type]
