# Generated by Django 6.0.5 on 2026-06-16 20:59

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_finance_ledger'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('fiscal_sign', models.CharField(blank=True, max_length=128)),
                ('qr_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('cash', 'Cash'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum'), ('bank_transfer', 'Bank transfer')], db_index=True, max_length=16)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_state', models.SmallIntegerField(blank=True, null=True)),
                ('provider_created_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('cancel_reason', models.SmallIntegerField(blank=True, null=True)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('allocation_status', models.CharField(choices=[('auto', 'Auto'), ('manual_review', 'Manual review'), ('allocated', 'Allocated')], default='auto', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.cashiershift')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ('payment', 'attempt_no'),
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('click_service_id', models.CharField(blank=True, max_length=64)),
                ('click_merchant_id', models.CharField(blank=True, max_length=64)),
                ('click_secret_key', core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('payme_merchant_id', models.CharField(blank=True, max_length=64)),
                ('payme_key', core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('payme_test_key', core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('uzum_merchant_id', models.CharField(blank=True, max_length=64)),
                ('uzum_api_key', core.fields.EncryptedCharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('provider',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('event_id', models.CharField(max_length=128)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='received', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='PaymentItem',
        ),
        migrations.AddField(
            model_name='fiscalreceipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_receipt', to='payments.payment'),
        ),
        migrations.AddConstraint(
            model_name='providerconfig',
            constraint=models.UniqueConstraint(fields=('provider',), name='providerconfig_one_per_provider'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider', 'event_id'], name='payments_we_provide_139ee0_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='webhookevent_provider_event_unique'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', 'attempt_no'], name='payments_pa_payment_19beca_idx'),
        ),
    ]
