# Generated by Django 6.0.5 on 2026-07-09 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_discount_single_use'),
        ('payments', '0002_fiscalreceipt_payment_paymentattempt_providerconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at', 'id'], name='payment_created_idx'),
        ),
    ]
