# Generated by Django 6.0.5 on 2026-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='principal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='principal_kind',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
