# Generated by Django 6.0.5 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rolemembership_unique_null_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="target_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="target_kind",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["identifier", "purpose", "target_kind", "target_id", "consumed_at"],
                name="otp_target_lookup_idx",
            ),
        ),
    ]
