# Generated by Django 6.0.7 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


def link_legacy_memberships(apps, schema_editor):
    from django_tenants.utils import get_public_schema_name

    if schema_editor.connection.schema_name == get_public_schema_name():
        return
    AccountType = apps.get_model("access", "AccountType")
    RoleMembership = apps.get_model("users", "RoleMembership")
    for slug, account_type_id in AccountType.objects.filter(is_system=True).values_list("slug", "id"):
        RoleMembership.objects.filter(role=slug, account_type_id__isnull=True).update(
            account_type_id=account_type_id
        )


def unlink_account_types(apps, schema_editor):
    from django_tenants.utils import get_public_schema_name

    if schema_editor.connection.schema_name == get_public_schema_name():
        return
    apps.get_model("users", "RoleMembership").objects.update(account_type_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_accounttype_accounttypepermission"),
        ("org", "0018_staffprofile_staff_phone_unique_nonblank_and_more"),
        ("users", "0005_otp_target_binding"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rolemembership",
            name="role_membership_unique_branch_role",
        ),
        migrations.AlterUniqueTogether(
            name="rolemembership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="rolemembership",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="access.accounttype",
            ),
        ),
        migrations.RunPython(link_legacy_memberships, unlink_account_types),
        migrations.AddConstraint(
            model_name="rolemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(account_type__isnull=True, department__isnull=True),
                fields=("user", "branch", "role"),
                name="role_membership_unique_branch_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(account_type__isnull=True, department__isnull=False),
                fields=("user", "branch", "department", "role"),
                name="legacy_membership_unique_scoped_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(account_type__isnull=False, department__isnull=True),
                fields=("user", "branch", "account_type"),
                name="account_type_membership_unique_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(account_type__isnull=False, department__isnull=False),
                fields=("user", "branch", "department", "account_type"),
                name="account_type_membership_unique_department",
            ),
        ),
    ]
