# Generated by Django 6.0.5 on 2026-06-26 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_cash', models.BooleanField(default=False)),
                ('default_amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RewardGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_grants', to='approvals.approvalrequest')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to=settings.AUTH_USER_MODEL)),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='rewards.rewardtype')),
            ],
            options={
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['recipient', 'granted_at'], name='rewards_rew_recipie_718c43_idx')],
            },
        ),
    ]
