# Generated by Django 6.0.7 on 2026-08-02 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0021_durable_center_settings'),
        ('students', '0011_protect_identity_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=8)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AcquisitionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_campaigns', to='org.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_campaigns', to='org.department')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='crm.leadsource')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('merged', 'Merged')], db_index=True, default='open', max_length=8)),
                ('owner_principal_kind', models.CharField(blank=True, max_length=16)),
                ('owner_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('identity_fingerprint', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('phone_fingerprint', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('email_fingerprint', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_by_principal_kind', models.CharField(max_length=16)),
                ('created_by_principal_id', models.PositiveBigIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_leads', to='org.branch')),
                ('canonical_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_duplicates', to='crm.crmlead')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_leads', to='org.department')),
                ('initial_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_leads', to='crm.acquisitioncampaign')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_crm_leads', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='crm_lead', to='students.studentprofile')),
                ('initial_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_leads', to='crm.leadsource')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('signals', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('dismissed', 'Dismissed'), ('merged', 'Merged')], db_index=True, default='pending', max_length=12)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_principal_kind', models.CharField(blank=True, max_length=16)),
                ('reviewed_by_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.CharField(blank=True, max_length=1000)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_candidates_left', to='crm.crmlead')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_candidates_right', to='crm.crmlead')),
            ],
            options={
                'ordering': ('-score', '-detected_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('purpose', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('assignee_principal_kind', models.CharField(max_length=16)),
                ('assignee_principal_id', models.PositiveBigIntegerField()),
                ('created_by_principal_kind', models.CharField(max_length=16)),
                ('created_by_principal_id', models.PositiveBigIntegerField()),
                ('resolved_by_principal_kind', models.CharField(blank=True, max_length=16)),
                ('resolved_by_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='crm.crmlead')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LeadMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.CharField(max_length=1000)),
                ('reviewed_by_principal_kind', models.CharField(max_length=16)),
                ('reviewed_by_principal_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merge_record', to='crm.leadduplicatecandidate')),
                ('canonical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_merges', to='crm.crmlead')),
                ('duplicate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merge_as_duplicate', to='crm.crmlead')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, max_length=64)),
                ('content', models.CharField(blank=True, max_length=160)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_principal_kind', models.CharField(max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='crm.acquisitioncampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='crm.crmlead')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='crm.leadsource')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('in_person', 'In person'), ('other', 'Other')], max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('outcome', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=2000)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_principal_kind', models.CharField(max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='touches', to='crm.crmlead')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('merged', 'Merged')], max_length=8)),
                ('to_state', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('merged', 'Merged')], max_length=8)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('actor_principal_kind', models.CharField(max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_history', to='crm.crmlead')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stage_exits', to='crm.pipelinestage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_entries', to='crm.pipelinestage')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CRMIdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_principal_kind', models.CharField(max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('key_hash', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('result_type', models.CharField(max_length=32)),
                ('result_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='crm_idempotency_age_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_principal_kind', 'actor_principal_id', 'key_hash'), name='crm_idempotency_actor_key')],
            },
        ),
        migrations.AddIndex(
            model_name='leadduplicatecandidate',
            index=models.Index(fields=['status', '-score', '-detected_at'], name='crm_duplicate_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicatecandidate',
            constraint=models.UniqueConstraint(fields=('left', 'right'), name='crm_duplicate_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicatecandidate',
            constraint=models.CheckConstraint(condition=models.Q(('left_id__lt', models.F('right_id'))), name='crm_dup_ordered'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicatecandidate',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='crm_dup_score_max'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicatecandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rationale', ''), ('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('reviewed_by_principal_id__isnull', True), ('reviewed_by_principal_kind', ''), ('status', 'pending')), models.Q(('status__in', ('dismissed', 'merged')), ('reviewed_by__isnull', False), ('reviewed_by_principal_kind__in', ('staff', 'teacher')), ('reviewed_by_principal_id__isnull', False), ('reviewed_at__isnull', False), ('rationale__gt', '')), _connector='OR'), name='crm_duplicate_review_state'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['lead', 'status', 'due_at', 'id'], name='crm_followup_next_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfollowup',
            index=models.Index(fields=['assignee_principal_kind', 'assignee_principal_id', 'status', 'due_at'], name='crm_followup_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadfollowup',
            constraint=models.CheckConstraint(condition=models.Q(('assignee_principal_kind__in', ('staff', 'teacher'))), name='crm_followup_assignee_kind'),
        ),
        migrations.AddConstraint(
            model_name='leadfollowup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolution_note', ''), ('resolved_at__isnull', True), ('resolved_by__isnull', True), ('resolved_by_principal_id__isnull', True), ('resolved_by_principal_kind', ''), ('status', 'pending')), models.Q(('status__in', ('completed', 'cancelled')), ('resolved_by__isnull', False), ('resolved_by_principal_kind__in', ('staff', 'teacher')), ('resolved_by_principal_id__isnull', False), ('resolved_at__isnull', False)), _connector='OR'), name='crm_followup_resolution_state'),
        ),
        migrations.AddConstraint(
            model_name='leadmerge',
            constraint=models.CheckConstraint(condition=models.Q(('canonical', models.F('duplicate')), _negated=True), name='crm_merge_distinct_leads'),
        ),
        migrations.AddIndex(
            model_name='leadattribution',
            index=models.Index(fields=['lead', '-occurred_at', '-id'], name='crm_attribution_idx'),
        ),
        migrations.AddIndex(
            model_name='leadattribution',
            index=models.Index(fields=['source', 'campaign', 'occurred_at'], name='crm_attr_funnel_idx'),
        ),
        migrations.AddIndex(
            model_name='leadattribution',
            index=models.Index(fields=['campaign', 'occurred_at', 'lead'], name='crm_attr_campaign_idx'),
        ),
        migrations.AddIndex(
            model_name='acquisitioncampaign',
            index=models.Index(fields=['branch', 'department', 'is_active'], name='crm_campaign_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='acquisitioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', True), ('branch__isnull', False), _connector='OR'), name='crm_campaign_dept_needs_branch'),
        ),
        migrations.AddConstraint(
            model_name='acquisitioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='crm_campaign_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='leadtouch',
            index=models.Index(fields=['lead', '-occurred_at', '-id'], name='crm_touch_timeline_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadtouch',
            constraint=models.CheckConstraint(condition=models.Q(('actor_principal_kind__in', ('staff', 'teacher'))), name='crm_touch_actor_kind'),
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['lead', '-created_at', '-id'], name='crm_stage_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadstagehistory',
            constraint=models.CheckConstraint(condition=models.Q(('actor_principal_kind__in', ('staff', 'teacher'))), name='crm_stage_actor_kind'),
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['branch', 'department', 'state', 'stage', '-created_at'], name='crm_lead_scope_state_idx'),
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['owner_principal_kind', 'owner_principal_id', 'state', '-created_at'], name='crm_lead_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['branch', '-created_at', 'id'], name='crm_lead_branch_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['-created_at', 'id'], name='crm_lead_created_idx'),
        ),
        migrations.AddIndex(
            model_name='crmlead',
            index=models.Index(fields=['state', '-created_at'], name='crm_lead_funnel_idx'),
        ),
        migrations.AddConstraint(
            model_name='crmlead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('owner_principal_id__isnull', True), ('owner_principal_kind', '')), models.Q(('owner__isnull', False), ('owner_principal_kind__in', ('staff', 'teacher')), ('owner_principal_id__isnull', False)), _connector='OR'), name='crm_lead_owner_principal_pair'),
        ),
        migrations.AddConstraint(
            model_name='crmlead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loss_reason__gt', ''), ('state', 'lost')), models.Q(models.Q(('state', 'lost'), _negated=True), ('loss_reason', '')), _connector='OR'), name='crm_lead_loss_reason_state'),
        ),
        migrations.AddConstraint(
            model_name='crmlead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_lead__isnull', False), ('state', 'merged')), models.Q(models.Q(('state', 'merged'), _negated=True), ('canonical_lead__isnull', True)), _connector='OR'), name='crm_lead_canonical_state'),
        ),
        migrations.AddConstraint(
            model_name='crmlead',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('canonical_lead_id')), _negated=True), name='crm_lead_not_own_canonical'),
        ),
        migrations.AddConstraint(
            model_name='crmlead',
            constraint=models.CheckConstraint(condition=models.Q(('created_by_principal_kind__in', ('staff', 'teacher')), ('created_by_principal_id__isnull', False)), name='crm_lead_creator_principal'),
        ),
    ]
