# Generated by Django 6.0.5 on 2026-07-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='audience_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='form',
            name='audience_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
