# Generated by Django 6.0.5 on 2026-06-12 00:12

import apps.schedule.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_initial'),
        ('org', '0002_initial'),
        ('schedule', '0001_initial'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The GiST exclusion constraints below need btree_gist (for the `=`
        # operator on room/teacher/cohort inside the exclusion). btree_gist is a
        # trusted extension in PG13+, so the non-superuser tenant role can install
        # it on its own database.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='scheduled', max_length=10)),
                ('detached_from_rule', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='cohorts.cohort')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='org.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rrule', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='org.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('branch', 'order', 'start_time'),
            },
        ),
        migrations.DeleteModel(
            name='ScheduleItem',
        ),
        migrations.AddField(
            model_name='lesson',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule.recurrencerule'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='term_unique_year_name'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='term_dates_ordered'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='schedule.term'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='schedule.term'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='org.branch'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='rule_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='rule_times_ordered'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['cohort', 'starts_at'], name='schedule_le_cohort__a1b9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'starts_at'], name='schedule_le_teacher_4ec590_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['room', 'starts_at'], name='schedule_le_room_id_4aeb0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='lesson_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('room__isnull', False), ('status', 'scheduled')), expressions=[(apps.schedule.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room', '=')], name='lesson_no_room_overlap'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'scheduled')), expressions=[(apps.schedule.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('teacher', '=')], name='lesson_no_teacher_overlap'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'scheduled')), expressions=[(apps.schedule.models.TsTzRange('starts_at', 'ends_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('cohort', '=')], name='lesson_no_cohort_overlap'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='timeslot_unique_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_times_ordered'),
        ),
    ]
