# Generated by Django 6.0.5 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_lessontype_lesson_lesson_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="auto_absence_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["status", "auto_absence_processed_at", "starts_at"],
                name="lesson_auto_absence_idx",
            ),
        ),
    ]
