# Generated by Django 6.0.5 on 2026-06-11 21:49

import apps.org.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('max_students', models.PositiveIntegerField(blank=True, null=True)),
                ('max_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BranchWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('branch', 'weekday'),
            },
        ),
        migrations.CreateModel(
            name='CenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_registration', models.BooleanField(default=False)),
                ('grading_scheme', models.CharField(choices=[('letter', 'Letter (A–F)'), ('gpa', 'GPA (0–4)'), ('percentage', 'Percentage (0–100)')], default='percentage', max_length=16)),
                ('late_threshold_minutes', models.PositiveSmallIntegerField(default=10)),
                ('attendance_correction_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('assignment_grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('max_upload_mb', models.PositiveIntegerField(default=200)),
                ('allowed_file_types', models.JSONField(default=apps.org.models._default_allowed_file_types)),
                ('currency_primary', models.CharField(default='UZS', max_length=3)),
                ('currency_secondary', models.CharField(default='USD', max_length=3)),
                ('fx_source', models.CharField(default='cbu', max_length=32)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(7, 0))),
                ('otp_channel_prefs', models.JSONField(default=apps.org.models._default_otp_channel_prefs)),
                ('otp_cooldown_seconds', models.PositiveSmallIntegerField(default=60)),
                ('student_id_pattern', models.CharField(default='{CODE}-{YYYY}-{NNNNN}', max_length=64)),
                ('center_code', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Center settings',
                'verbose_name_plural': 'Center settings',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('branch', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('branch', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BranchHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('is_working_day_override', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='org.branch')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
