# Generated by Django 6.0.5 on 2026-06-11 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtransfer',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='org.branch'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='org.branch'),
        ),
        migrations.AddField(
            model_name='branchtransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchworkinghours',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='org.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='org.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='org.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='branchholiday',
            unique_together={('branch', 'date')},
        ),
        migrations.AddConstraint(
            model_name='branchworkinghours',
            constraint=models.CheckConstraint(condition=models.Q(('is_closed', True), ('opens_at__lt', models.F('closes_at')), _connector='OR'), name='working_hours_open_before_close_or_closed'),
        ),
        migrations.AlterUniqueTogether(
            name='branchworkinghours',
            unique_together={('branch', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('branch', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('branch', 'name')},
        ),
    ]
