# Generated by Django 6.0.5 on 2026-06-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='auto_absent_after_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
