# Generated by Django 6.0.5 on 2026-06-12 01:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_centersettings_auto_absent_after_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='academic_warning_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('60'), max_digits=5),
        ),
        migrations.AddField(
            model_name='centersettings',
            name='honor_roll_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('90'), max_digits=5),
        ),
    ]
