# Generated by Django 6.0.5 on 2026-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_centersettings_academic_warning_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='assignment_max_resubmits',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
