# Generated by Django 6.0.5 on 2026-06-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_centersettings_assignment_max_resubmits'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='storage_quota_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
