# Generated by Django 6.0.5 on 2026-06-16 20:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_centersettings_storage_quota_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='fx_rate_usd_manual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='centersettings',
            name='payment_reminder_interval_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='centersettings',
            name='sibling_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
