# Generated by Django 6.0.5 on 2026-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_centersettings_fx_rate_usd_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='ai_exam_generation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
