# Generated by Django 6.0.5 on 2026-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_centersettings_ai_exam_generation_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='default_language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='', help_text='Default notification language; blank uses the en→uz fallback.', max_length=8),
        ),
    ]
