# Generated by Django 6.0.5 on 2026-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_centersettings_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='require_group_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
