# Generated by Django 6.0.5 on 2026-06-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_centersettings_require_group_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='placement_allowed_question_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
