# Generated by Django 6.0.5 on 2026-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_centersettings_placement_allowed_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='penalty_escalation_threshold',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
