# Generated by Django 6.0.5 on 2026-06-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_centersettings_penalty_escalation_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='show_classroom_rank',
            field=models.BooleanField(default=True),
        ),
    ]
