# Generated by Django 6.0.5 on 2026-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_centersettings_show_classroom_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='absence_deduction_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='centersettings',
            name='absence_deduction_excused_only',
            field=models.BooleanField(default=True),
        ),
    ]
