# Generated by Django 6.0.5 on 2026-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_centersettings_absence_deduction_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersettings',
            name='placement_test_creation_mobile_only',
            field=models.BooleanField(default=False),
        ),
    ]
