# Generated by Django 6.0.5 on 2026-07-10 12:11

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_staff_profiles(apps, schema_editor):
    """Create a StaffProfile for each tenant User who holds an active RoleMembership but has
    NO student/teacher/parent profile (pure staff), copying identity + credentials off the
    User. Deterministic (no role-name heuristic). Runs per tenant schema — the public schema
    has no org table, so platform admins never get a StaffProfile (they stay /admin/-only)."""
    User = apps.get_model("users", "User")
    RoleMembership = apps.get_model("users", "RoleMembership")
    StaffProfile = apps.get_model("org", "StaffProfile")
    has_profile: set[int] = set()
    for label in ("students.StudentProfile", "teachers.TeacherProfile", "parents.ParentProfile"):
        app_label, model_name = label.split(".")
        model = apps.get_model(app_label, model_name)
        has_profile |= set(model.objects.values_list("user_id", flat=True))
    staff_user_ids = (
        set(RoleMembership.objects.filter(revoked_at__isnull=True).values_list("user_id", flat=True))
        - has_profile
    )
    for u in User.objects.filter(pk__in=staff_user_ids).iterator():
        StaffProfile.objects.get_or_create(
            user_id=u.pk,
            defaults={
                "username": u.username,
                "password": u.password,
                "is_active": u.is_active,
                "last_login_at": u.last_login,
                "first_name": u.first_name or "",
                "last_name": u.last_name or "",
                "middle_name": u.middle_name or "",
                "phone": u.phone or "",
                "email": u.email or "",
                "birthdate": u.birthdate,
                "gender": u.gender or "",
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_centersettings_placement_test_creation_mobile_only'),
        ('students', '0006_student_owns_identity'),
        ('teachers', '0004_teacher_owns_identity'),
        ('parents', '0004_parent_owns_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Login identifier for this role account.', max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.RunPython(backfill_staff_profiles, noop),
    ]
