# Generated by Django 6.0.5 on 2026-07-13 15:17

import django.db.models.deletion
from django.contrib.auth.hashers import is_password_usable, make_password
from django.conf import settings
from django.db import migrations, models


def cut_over_role_passwords(apps, schema_editor):
    """Make each role table authoritative, then disable every non-admin bridge login."""
    User = apps.get_model("users", "User")
    role_models = (
        ("student", apps.get_model("students", "StudentProfile")),
        ("teacher", apps.get_model("teachers", "TeacherProfile")),
        ("parent", apps.get_model("parents", "ParentProfile")),
        ("staff", apps.get_model("org", "StaffProfile")),
    )
    bridge_ids: set[int] = set()
    used_usernames: set[str] = set()
    for kind, model in role_models:
        for account in model.objects.select_related("user").order_by("pk").iterator():
            base = (account.username or account.user.username or f"{kind}-{account.pk}")[:130]
            username = base
            counter = 1
            while username in used_usernames:
                username = f"{base}-{kind}-{account.pk}-{counter}"[:150]
                counter += 1
            used_usernames.add(username)
            if account.username != username:
                account.username = username
                account.save(update_fields=["username"])
    # Copy every current bridge password before disabling any bridge: older data can
    # legitimately have more than one role profile attached to the same User.
    for _kind, model in role_models:
        for account in model.objects.select_related("user").iterator():
            bridge_ids.add(account.user_id)
            if is_password_usable(account.user.password):
                account.password = account.user.password
                account.save(update_fields=["password"])
    unusable = make_password(None)
    User.objects.filter(pk__in=bridge_ids, is_staff=False, is_superuser=False).update(password=unusable)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0016_role_credentials"),
        ("parents", "0006_alter_parentprofile_user"),
        ("students", "0008_alter_studentprofile_user"),
        ("teachers", "0006_alter_teacherprofile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(cut_over_role_passwords, noop),
    ]
