# Generated by Django 6.0.5 on 2026-06-26 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('finance', '0003_paymentmethod_expense'),
        ('org', '0009_centersettings_default_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='org.branch')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.ledgerentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='approvals.approvalrequest')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='finance.paymentmethod')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['loan', 'created_at'], name='loans_loanr_loan_id_bb4da5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_uzs__gt', 0)), name='loan_repayment_amount_positive')],
            },
        ),
    ]
