# Generated by Django 6.0.5 on 2026-07-09 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_delete_attendanceitem_and_more'),
        ('schedule', '0003_lessontype_lesson_lesson_type_and_more'),
        ('students', '0003_studentprofile_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-created_at', 'id'], name='attnrec_created_idx'),
        ),
    ]
