# Generated by Django 6.0.5 on 2026-06-16 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("ai_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("assignment_feedback", "Assignment feedback"),
                            ("exam_generation", "Exam generation"),
                            ("content_summary", "Content summary"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveSmallIntegerField()),
                ("system_prompt", models.TextField()),
                ("user_template", models.TextField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("effort", models.CharField(default="medium", max_length=16)),
                ("token_cost_cap", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI prompt",
                "verbose_name_plural": "AI prompts",
                "ordering": ("feature", "-version"),
            },
        ),
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("assignment_feedback", "Assignment feedback"),
                            ("exam_generation", "Exam generation"),
                            ("content_summary", "Content summary"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("denied_budget", "Denied (budget)"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("source_app", models.CharField(max_length=32)),
                ("source_id", models.PositiveBigIntegerField()),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_creation_tokens", models.PositiveIntegerField(default=0)),
                ("cost_microusd", models.BigIntegerField(default=0)),
                ("redaction_map", core.fields.EncryptedTextField(blank=True, default="")),
                ("output_text", models.TextField(blank=True)),
                ("error_detail", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "AI request",
                "verbose_name_plural": "AI requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TenantAIBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("daily_token_limit", models.PositiveIntegerField(default=100000)),
                ("monthly_token_limit", models.PositiveIntegerField(default=2000000)),
                ("tokens_used_today", models.PositiveBigIntegerField(default=0)),
                ("tokens_used_month", models.PositiveBigIntegerField(default=0)),
                ("day_anchor", models.DateField(default=django.utils.timezone.localdate)),
                ("month_anchor", models.DateField(default=django.utils.timezone.localdate)),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant AI budget",
                "verbose_name_plural": "Tenant AI budgets",
                "ordering": ("pk",),
            },
        ),
        migrations.DeleteModel(
            name="AiItem",
        ),
        migrations.AddIndex(
            model_name="aiprompt",
            index=models.Index(fields=["feature", "is_active"], name="ai_app_aipr_feature_10f2fc_idx"),
        ),
        migrations.AddConstraint(
            model_name="aiprompt",
            constraint=models.UniqueConstraint(
                fields=("feature", "version"), name="ai_prompt_unique_feature_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="aiprompt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("feature",),
                name="ai_prompt_one_active_per_feature",
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="ai_app.aiprompt"
            ),
        ),
        migrations.AddField(
            model_name="airequest",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantaibudget",
            constraint=models.CheckConstraint(condition=models.Q(("pk", 1)), name="ai_budget_singleton_pk1"),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(fields=["feature", "status"], name="ai_app_aire_feature_bc42f1_idx"),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(fields=["source_app", "source_id"], name="ai_app_aire_source__6e7008_idx"),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(fields=["created_at"], name="ai_app_aire_created_12fba6_idx"),
        ),
    ]
