# Generated by Django 6.0.5 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_seed_ai_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='reserved_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
