# Generated by Django 6.0.5 on 2026-06-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_seed_placement_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='feature',
            field=models.CharField(choices=[('assignment_feedback', 'Assignment feedback'), ('exam_generation', 'Exam generation'), ('content_summary', 'Content summary'), ('placement_generation', 'Placement test generation')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='feature',
            field=models.CharField(choices=[('assignment_feedback', 'Assignment feedback'), ('exam_generation', 'Exam generation'), ('content_summary', 'Content summary'), ('placement_generation', 'Placement test generation')], db_index=True, max_length=32),
        ),
    ]
