# Generated by Django 6.0.5 on 2026-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0012_seed_material_generation_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='feature',
            field=models.CharField(choices=[('assignment_feedback', 'Assignment feedback'), ('exam_generation', 'Exam generation'), ('content_summary', 'Content summary'), ('placement_generation', 'Placement test generation'), ('form_analysis', 'Form response analysis'), ('writing_marking', 'Placement writing marking'), ('material_generation', 'Library material generation'), ('template_generation', 'Message template generation')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='feature',
            field=models.CharField(choices=[('assignment_feedback', 'Assignment feedback'), ('exam_generation', 'Exam generation'), ('content_summary', 'Content summary'), ('placement_generation', 'Placement test generation'), ('form_analysis', 'Form response analysis'), ('writing_marking', 'Placement writing marking'), ('material_generation', 'Library material generation'), ('template_generation', 'Message template generation')], db_index=True, max_length=32),
        ),
    ]
