# Generated by Django 6.0.5 on 2026-07-09 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('hourly', 'Per taught hour'), ('percent_of_collected_tuition', '% of collected tuition'), ('flat_monthly', 'Flat amount per period')], max_length=32)),
                ('hourly_rate_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('flat_amount_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tuition_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_policy', to='teachers.teacherprofile')),
            ],
        ),
    ]
