# Generated by Django 6.0.5 on 2026-07-10 11:47

from django.db import migrations, models


def backfill_identity_from_user(apps, schema_editor):
    """Copy each existing teacher's identity off their User onto the TeacherProfile,
    which now owns it (role-native-auth migration). Runs once per tenant schema."""
    TeacherProfile = apps.get_model("teachers", "TeacherProfile")
    for tp in TeacherProfile.objects.select_related("user").iterator():
        u = tp.user
        TeacherProfile.objects.filter(pk=tp.pk).update(
            first_name=u.first_name or "",
            last_name=u.last_name or "",
            middle_name=u.middle_name or "",
            phone=u.phone or "",
            email=u.email or "",
            birthdate=u.birthdate,
            gender=u.gender or "",
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_payoutpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=8),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.RunPython(backfill_identity_from_user, noop),
    ]
