# Generated by Django 6.0.5 on 2026-07-14

import django.db.models.functions.text
from django.db import migrations, models


SYSTEM_TYPES = (
    {
        "name": "Main Teacher",
        "slug": "main-teacher",
        "description": "Primary teaching responsibility for a cohort.",
        "is_default": True,
        "sort_order": 10,
    },
    {
        "name": "Video Teacher",
        "slug": "video-teacher",
        "description": "Teacher responsible for video or remote instruction.",
        "is_default": False,
        "sort_order": 20,
    },
    {
        "name": "Assistant",
        "slug": "assistant",
        "description": "Teaching assistant assigned to a cohort.",
        "is_default": False,
        "sort_order": 30,
    },
    {
        "name": "Co-teacher",
        "slug": "co-teacher",
        "description": "Teacher sharing responsibility for a cohort.",
        "is_default": False,
        "sort_order": 40,
    },
)


def seed_teacher_types(apps, schema_editor):
    teacher_type = apps.get_model("teachers", "TeacherType")
    for item in SYSTEM_TYPES:
        defaults = {
            "name": item["name"],
            "description": item["description"],
            "is_active": True,
            "is_system": True,
            "is_default": item["is_default"],
            "sort_order": item["sort_order"],
        }
        teacher_type.objects.update_or_create(slug=item["slug"], defaults=defaults)


def unseed_teacher_types(apps, schema_editor):
    teacher_type = apps.get_model("teachers", "TeacherType")
    teacher_type.objects.filter(slug__in=[item["slug"] for item in SYSTEM_TYPES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0007_teacherprofile_teacher_phone_unique_nonblank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("sort_order", "name", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="teacher_type_name_unique_ci",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("slug"),
                        name="teacher_type_slug_unique_ci",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="one_default_teacher_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("is_default", False), ("is_active", True), _connector="OR"),
                        name="teacher_type_default_requires_active",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_teacher_types, unseed_teacher_types),
    ]
