# Generated by Django 6.0.5 on 2026-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_delete_audititem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('otp_request', 'OTP request'), ('otp_verify', 'OTP verify'), ('impersonate', 'Impersonate'), ('export', 'Export')], db_index=True, max_length=32),
        ),
    ]
