# Generated by Django 6.0.5 on 2026-08-02

from django.db import migrations, models

HARDEN_TRIGGER_SQL = r"""
CREATE OR REPLACE FUNCTION audit_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- Retention may delete, but may never update historical content.
    IF TG_OP = 'DELETE'
       AND current_setting('starforge.audit_maintenance', true) = 'retention-delete'
       AND (
            (
                OLD.resource_type IN (
                    'finance.Invoice',
                    'payments.Payment',
                    'finance.Refund',
                    'academics.Grade',
                    'academics.ExamResult'
                )
                AND OLD.created_at < CURRENT_TIMESTAMP - INTERVAL '2555 days'
            )
            OR
            (
                OLD.resource_type NOT IN (
                    'finance.Invoice',
                    'payments.Payment',
                    'finance.Refund',
                    'academics.Grade',
                    'academics.ExamResult'
                )
                AND OLD.created_at < CURRENT_TIMESTAMP - INTERVAL '365 days'
            )
       ) THEN
        RETURN OLD;
    END IF;

    -- The reviewed legacy-scope command may transition only unresolved scope
    -- columns. Every pre-existing audit field must remain byte-for-byte equal.
    IF TG_OP = 'UPDATE'
       AND current_setting('starforge.audit_maintenance', true) = 'scope-backfill'
       AND OLD.scope_status = 'unresolved'
       AND NEW.scope_status IN ('scoped', 'organization')
       AND (
            (NEW.scope_status = 'scoped' AND NEW.scope_branch_id IS NOT NULL)
            OR
            (NEW.scope_status = 'organization'
             AND NEW.scope_branch_id IS NULL
             AND NEW.scope_department_id IS NULL)
       )
       AND (((to_jsonb(NEW) - 'scope_status') - 'scope_branch_id') - 'scope_department_id')
           = (((to_jsonb(OLD) - 'scope_status') - 'scope_branch_id') - 'scope_department_id') THEN
        RETURN NEW;
    END IF;

    -- Tests need deterministic aging/cursor fixtures. This capability is
    -- accepted only in a database whose name is explicitly test-prefixed.
    IF left(current_database(), 5) = 'test_'
       AND current_setting('starforge.audit_test', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;

    -- AuditLog.actor uses SET NULL so deleting a user preserves history. Permit
    -- exactly that FK-maintenance change while rejecting every content edit.
    IF TG_OP = 'UPDATE'
       AND OLD.actor_id IS NOT NULL
       AND NEW.actor_id IS NULL
       AND (to_jsonb(NEW) - 'actor_id') = (to_jsonb(OLD) - 'actor_id') THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'audit logs are append-only'
        USING ERRCODE = '55000';
END;
$$;
"""

RESTORE_TRIGGER_SQL = r"""
CREATE OR REPLACE FUNCTION audit_reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF current_setting('starforge.audit_maintenance', true) = 'on' THEN
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END IF;
    IF TG_OP = 'UPDATE'
       AND OLD.actor_id IS NOT NULL
       AND NEW.actor_id IS NULL
       AND (to_jsonb(NEW) - 'actor_id') = (to_jsonb(OLD) - 'actor_id') THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'audit logs are append-only'
        USING ERRCODE = '55000';
END;
$$;
"""

BACKFILL_SENSITIVITY_SQL = r"""
SET LOCAL starforge.audit_maintenance = 'on';
UPDATE audit_auditlog
SET sensitivity = 'compensation'
WHERE resource_type IN ('teachers.TeacherProfile', 'teachers.PayoutPolicy')
   OR (
        resource_type = 'approvals.ApprovalRequest'
        AND (
            COALESCE(before ->> 'kind', '') = 'salary_prep'
            OR COALESCE(after ->> 'kind', '') = 'salary_prep'
        )
   )
   OR (
        resource_type = 'approvals.LedgerEntry'
        AND (
            COALESCE(before ->> 'entry_type', '') = 'salary_prep'
            OR COALESCE(after ->> 'entry_type', '') = 'salary_prep'
        )
   );
"""

CLASSIFY_INSERT_SQL = r"""
CREATE OR REPLACE FUNCTION audit_classify_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.resource_type IN ('teachers.TeacherProfile', 'teachers.PayoutPolicy')
       OR (
            NEW.resource_type = 'approvals.ApprovalRequest'
            AND (
                COALESCE(NEW.before ->> 'kind', '') = 'salary_prep'
                OR COALESCE(NEW.after ->> 'kind', '') = 'salary_prep'
            )
       )
       OR (
            NEW.resource_type = 'approvals.LedgerEntry'
            AND (
                COALESCE(NEW.before ->> 'entry_type', '') = 'salary_prep'
                OR COALESCE(NEW.after ->> 'entry_type', '') = 'salary_prep'
            )
       ) THEN
        NEW.sensitivity = 'compensation';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_log_classify_insert ON audit_auditlog;
CREATE TRIGGER audit_log_classify_insert
BEFORE INSERT ON audit_auditlog
FOR EACH ROW EXECUTE FUNCTION audit_classify_insert();
"""

DROP_CLASSIFY_INSERT_SQL = r"""
DROP TRIGGER IF EXISTS audit_log_classify_insert ON audit_auditlog;
DROP FUNCTION IF EXISTS audit_classify_insert();
"""


class Migration(migrations.Migration):
    dependencies = [("audit", "0004_auditlog_database_immutability")]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="scope_branch_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="scope_department_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="scope_status",
            field=models.CharField(
                choices=[
                    ("scoped", "Scoped"),
                    ("organization", "Organization-wide"),
                    ("unresolved", "Unresolved"),
                ],
                db_index=True,
                default="unresolved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="sensitivity",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("compensation", "Compensation"),
                ],
                db_default="standard",
                db_index=True,
                default="standard",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["scope_status", "scope_branch_id", "-created_at", "-id"],
                name="audit_scope_branch_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=[
                    "scope_status",
                    "scope_branch_id",
                    "scope_department_id",
                    "-created_at",
                    "-id",
                ],
                name="audit_scope_dept_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(scope_status="scoped", scope_branch_id__isnull=False)
                    | models.Q(
                        scope_status__in=("organization", "unresolved"),
                        scope_branch_id__isnull=True,
                        scope_department_id__isnull=True,
                    )
                ),
                name="audit_scope_status_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(scope_department_id__isnull=True) | models.Q(scope_branch_id__isnull=False)
                ),
                name="audit_scope_department_needs_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditlog",
            constraint=models.CheckConstraint(
                condition=models.Q(sensitivity__in=("standard", "compensation")),
                name="audit_sensitivity_valid",
            ),
        ),
        migrations.RunSQL(BACKFILL_SENSITIVITY_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(CLASSIFY_INSERT_SQL, DROP_CLASSIFY_INSERT_SQL),
        migrations.RunSQL(HARDEN_TRIGGER_SQL, RESTORE_TRIGGER_SQL),
    ]
