# Generated by Django 6.0.5 on 2026-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_seed_report_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='recipient_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
