# Generated by Django 6.0.7 on 2026-08-02 03:47

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0004_approval_idempotency'),
        ('finance', '0009_invoice_historical_scope'),
        ('org', '0021_durable_center_settings'),
        ('teachers', '0010_alter_payoutpolicy_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user_id_snapshot', models.PositiveBigIntegerField()),
                ('teacher_name_snapshot', models.CharField(max_length=255)),
                ('teacher_code_snapshot', models.CharField(max_length=150)),
                ('payout_policy_id_snapshot', models.PositiveBigIntegerField()),
                ('payout_method_snapshot', models.CharField(max_length=32)),
                ('payout_policy_snapshot', models.JSONField(default=dict)),
                ('calculation_breakdown', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=3)),
                ('base_amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('bonus_amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deduction_amount_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_at_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_line_items', to='org.branch')),
                ('department_at_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_line_items', to='org.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_line_items', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ('teacher_name_snapshot', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction')], max_length=16)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('effective_period_start', models.DateField()),
                ('effective_period_end', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], db_index=True, default='pending', max_length=16)),
                ('created_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('created_principal_id', models.PositiveBigIntegerField()),
                ('decided_principal_kind', models.CharField(blank=True, choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('decided_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('operation_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='org.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='org.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='teachers.teacherprofile')),
                ('applied_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payroll.payrolllineitem')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPayslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payslip', to='payroll.payrolllineitem')),
            ],
            options={
                'ordering': ('-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('organization_timezone', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('payment_in_progress', 'Payment in progress'), ('paid', 'Paid')], db_index=True, default='draft', max_length=24)),
                ('correction_reason', models.CharField(blank=True, max_length=255)),
                ('created_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('created_principal_id', models.PositiveBigIntegerField()),
                ('run_principal_kind', models.CharField(blank=True, choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('run_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_principal_kind', models.CharField(blank=True, choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('approved_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rejected_principal_kind', models.CharField(blank=True, choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('rejected_principal_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('run_idempotency_key_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('run_fingerprint', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('base_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bonus_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deduction_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('paid_total_uzs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='org.branch')),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='payroll.payrollperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='org.department')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_start', '-id'),
            },
        ),
        migrations.AddField(
            model_name='payrolllineitem',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='payroll.payrollperiod'),
        ),
        migrations.CreateModel(
            name='PayrollExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=8)),
                ('filters', models.JSONField(default=dict)),
                ('requested_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('requested_principal_id', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('operation_fingerprint', models.CharField(max_length=64)),
                ('s3_key', models.CharField(blank=True, max_length=512)),
                ('file_bytes', models.PositiveBigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('run', 'Run'), ('approve', 'Approve'), ('reject', 'Reject'), ('payment', 'Payment'), ('reversal', 'Reversal')], max_length=16)),
                ('actor_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('operation_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payroll.payrollperiod')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Payment'), ('reversal', 'Reversal')], default='payment', max_length=16)),
                ('amount_uzs', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('external_reference', models.CharField(max_length=128)),
                ('paid_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('recorded_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('recorded_principal_id', models.PositiveBigIntegerField()),
                ('idempotency_key_hash', models.CharField(max_length=64, unique=True)),
                ('operation_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_reconciliation', to='approvals.ledgerentry')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='payroll.payrolllineitem')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_reconciliations', to='finance.paymentmethod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='payroll.payrollreconciliation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('released', 'Released')], max_length=16)),
                ('actor_principal_kind', models.CharField(choices=[('staff', 'Staff'), ('teacher', 'Teacher')], max_length=16)),
                ('actor_principal_id', models.PositiveBigIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('operation_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payroll.payrolladjustment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['adjustment', 'created_at', 'id'], name='pay_adj_event_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['branch', 'department', 'effective_period_start', 'effective_period_end', 'state'], name='pay_adjust_scope_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['teacher', 'state', 'created_at'], name='pay_adjust_teacher_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_uzs__gt', 0)), name='pay_adjust_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_period_end__gte', models.F('effective_period_start'))), name='pay_adjust_dates_ok'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_principal_id__isnull', True), ('decided_principal_kind', '')), models.Q(models.Q(('decided_principal_kind', ''), _negated=True), ('decided_principal_id__isnull', False), ('decided_at__isnull', False)), _connector='OR'), name='pay_adjust_decider_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('applied_line__isnull', False), ('state', 'applied')), models.Q(models.Q(('state', 'applied'), _negated=True), ('applied_line__isnull', True)), _connector='OR'), name='pay_adjust_applied_shape'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['branch', 'department', 'period_start', 'period_end', 'status'], name='payroll_scope_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status', 'pay_date', 'id'], name='payroll_status_paydate_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='pay_period_dates_ok'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('pay_date__isnull', True), ('pay_date__gte', models.F('period_end')), _connector='OR'), name='pay_period_paydate_ok'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('line_count__gte', 0)), name='pay_period_line_count_ok'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('base_total_uzs__gte', 0), ('bonus_total_uzs__gte', 0), ('deduction_total_uzs__gte', 0), ('net_total_uzs__gte', 0), ('paid_total_uzs__gte', 0), ('paid_total_uzs__lte', models.F('net_total_uzs'))), name='pay_period_totals_ok'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_of__isnull', True), ('correction_reason', '')), models.Q(('correction_of__isnull', False), models.Q(('correction_reason', ''), _negated=True)), _connector='OR'), name='pay_period_correction_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('run_principal_id__isnull', True), ('run_principal_kind', '')), models.Q(models.Q(('run_principal_kind', ''), _negated=True), ('run_principal_id__isnull', False)), _connector='OR'), name='pay_period_run_actor_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approved_principal_id__isnull', True), ('approved_principal_kind', '')), models.Q(models.Q(('approved_principal_kind', ''), _negated=True), ('approved_principal_id__isnull', False)), _connector='OR'), name='pay_period_approve_actor_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rejected_principal_id__isnull', True), ('rejected_principal_kind', '')), models.Q(models.Q(('rejected_principal_kind', ''), _negated=True), ('rejected_principal_id__isnull', False)), _connector='OR'), name='pay_period_reject_actor_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('run_fingerprint', ''), ('run_idempotency_key_hash__isnull', True)), models.Q(('run_idempotency_key_hash__isnull', False), models.Q(('run_fingerprint', ''), _negated=True)), _connector='OR'), name='pay_period_run_key_shape'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True), ('department__isnull', True)), fields=('branch', 'period_start', 'period_end'), name='pay_period_unique_branch_window'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True), ('department__isnull', False)), fields=('branch', 'department', 'period_start', 'period_end'), name='pay_period_unique_dept_window'),
        ),
        migrations.AddIndex(
            model_name='payrolllineitem',
            index=models.Index(fields=['period', 'teacher', 'id'], name='pay_line_period_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolllineitem',
            index=models.Index(fields=['branch_at_run', 'department_at_run', 'created_at', 'id'], name='pay_line_scope_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrolllineitem',
            constraint=models.UniqueConstraint(fields=('period', 'teacher'), name='pay_line_unique_teacher'),
        ),
        migrations.AddConstraint(
            model_name='payrolllineitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount_uzs__gte', 0), ('bonus_amount_uzs__gte', 0), ('deduction_amount_uzs__gte', 0), ('net_amount_uzs__gte', 0)), name='pay_line_amounts_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrolllineitem',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount_uzs', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('base_amount_uzs'), '+', models.F('bonus_amount_uzs')), '-', models.F('deduction_amount_uzs')))), name='pay_line_net_matches'),
        ),
        migrations.AddIndex(
            model_name='payrollexport',
            index=models.Index(fields=['period', 'status', 'created_at'], name='pay_export_period_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollexport',
            index=models.Index(fields=['status', 'created_at'], name='pay_export_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiodevent',
            index=models.Index(fields=['period', 'created_at', 'id'], name='pay_event_period_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiodevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idempotency_key_hash__isnull', True), ('operation_fingerprint', '')), models.Q(('idempotency_key_hash__isnull', False), models.Q(('operation_fingerprint', ''), _negated=True)), _connector='OR'), name='pay_event_key_shape'),
        ),
        migrations.AddIndex(
            model_name='payrollreconciliation',
            index=models.Index(fields=['line_item', 'kind', 'created_at'], name='pay_recon_line_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollreconciliation',
            index=models.Index(fields=['paid_at', 'id'], name='pay_recon_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollreconciliation',
            constraint=models.UniqueConstraint(fields=('payment_method', 'external_reference'), name='pay_recon_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_uzs__gt', 0)), name='pay_recon_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'payment'), ('reverses__isnull', True)), models.Q(('kind', 'reversal'), ('reverses__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='pay_recon_reversal_shape'),
        ),
    ]
