# Generated by Django 6.0.5 on 2026-06-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=32)),
                ('permission', models.CharField(max_length=64)),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('revoke', 'Revoke')], max_length=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('role', 'permission'),
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='one_override_per_role_permission'), models.CheckConstraint(condition=models.Q(('permission', '*:*'), _negated=True), name='no_master_wildcard_override')],
            },
        ),
    ]
