# Generated by Django 6.0.7 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


def seed_system_account_types(apps, schema_editor):
    from django_tenants.utils import get_public_schema_name

    if schema_editor.connection.schema_name == get_public_schema_name():
        return

    from core.permissions import ROLE_PERMISSION_MATRIX

    AccountType = apps.get_model("access", "AccountType")
    AccountTypePermission = apps.get_model("access", "AccountTypePermission")
    kind_by_role = {
        "teacher": "teacher",
        "student": "student",
        "parent": "parent",
    }
    for role, permissions in ROLE_PERMISSION_MATRIX.items():
        account_type, _created = AccountType.objects.update_or_create(
            slug=role,
            defaults={
                "name": role.replace("_", " ").title(),
                "account_kind": kind_by_role.get(role, "staff"),
                "description": f"System compatibility account type for {role}.",
                "is_active": True,
                "is_system": True,
            },
        )
        AccountTypePermission.objects.bulk_create(
            [
                AccountTypePermission(account_type_id=account_type.pk, permission=permission)
                for permission in sorted(permissions)
            ],
            ignore_conflicts=True,
        )


def remove_system_account_types(apps, schema_editor):
    from django_tenants.utils import get_public_schema_name

    if schema_editor.connection.schema_name == get_public_schema_name():
        return
    apps.get_model("access", "AccountType").objects.filter(is_system=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "account_kind",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("parent", "Parent"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("account_kind", "name", "pk")},
        ),
        migrations.CreateModel(
            name="AccountTypePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_rows",
                        to="access.accounttype",
                    ),
                ),
            ],
            options={
                "ordering": ("account_type_id", "permission"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_type", "permission"),
                        name="one_grant_per_account_type_permission",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_system_account_types, remove_system_account_types),
    ]
