from django.urls import path

from apps.crm.views.v1.crm_views import (
    campaigns_collection_view,
    duplicate_dismiss_view,
    duplicate_merge_view,
    duplicates_collection_view,
    follow_up_cancel_view,
    follow_up_complete_view,
    follow_up_register_view,
    funnel_view,
    lead_attributions_view,
    lead_detail_view,
    lead_duplicate_detect_view,
    lead_follow_ups_view,
    lead_owner_view,
    lead_stage_history_view,
    lead_touches_view,
    lead_transition_view,
    leads_collection_view,
    sources_collection_view,
    stage_detail_view,
    stages_collection_view,
)

urlpatterns = [
    path("stages/", stages_collection_view, name="crm-stages"),
    path("stages/<int:pk>/", stage_detail_view, name="crm-stage-detail"),
    path("sources/", sources_collection_view, name="crm-sources"),
    path("campaigns/", campaigns_collection_view, name="crm-campaigns"),
    path("funnel/", funnel_view, name="crm-funnel"),
    path("duplicates/", duplicates_collection_view, name="crm-duplicates"),
    path("duplicates/<int:pk>/dismiss/", duplicate_dismiss_view, name="crm-duplicate-dismiss"),
    path("duplicates/<int:pk>/merge/", duplicate_merge_view, name="crm-duplicate-merge"),
    path("follow-ups/", follow_up_register_view, name="crm-follow-ups"),
    path("follow-ups/<int:pk>/complete/", follow_up_complete_view, name="crm-follow-up-complete"),
    path("follow-ups/<int:pk>/cancel/", follow_up_cancel_view, name="crm-follow-up-cancel"),
    path("leads/", leads_collection_view, name="crm-leads"),
    path("leads/<int:pk>/", lead_detail_view, name="crm-lead-detail"),
    path("leads/<int:pk>/owner/", lead_owner_view, name="crm-lead-owner"),
    path("leads/<int:pk>/transition/", lead_transition_view, name="crm-lead-transition"),
    path("leads/<int:pk>/stage-history/", lead_stage_history_view, name="crm-lead-stage-history"),
    path("leads/<int:pk>/touches/", lead_touches_view, name="crm-lead-touches"),
    path("leads/<int:pk>/follow-ups/", lead_follow_ups_view, name="crm-lead-follow-ups"),
    path("leads/<int:pk>/attributions/", lead_attributions_view, name="crm-lead-attributions"),
    path("leads/<int:pk>/detect-duplicates/", lead_duplicate_detect_view, name="crm-lead-detect-duplicates"),
]
