# Generated by Django 6.0.5 on 2026-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_seed_default_templates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_47e85c_idx',
            old_name='notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notif_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdelivery',
            new_name='notificatio_notific_7707f8_idx',
            old_name='notif_delivery_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_a544c1_idx',
            old_name='notif_pref_user_event_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationtemplate',
            new_name='notificatio_event_t_72ad4d_idx',
            old_name='notif_tmpl_evt_chan_loc_idx',
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('in_app', 'In-app')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('schedule.lesson_reminder', 'Lesson reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('in_app', 'In-app')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('schedule.lesson_reminder', 'Lesson reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended')], db_index=True, max_length=64),
        ),
    ]
