# Generated by Django 6.0.5 on 2026-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('schedule.lesson_reminder', 'Lesson reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('schedule.lesson_reminder', 'Lesson reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('schedule.lesson_reminder', 'Lesson reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed')], db_index=True, max_length=64),
        ),
    ]
