# Generated by Django 6.0.7 on 2026-08-01

from django.conf import settings
from django.db import migrations, models

RECIPIENT_GUARDS_SQL = r"""
CREATE OR REPLACE FUNCTION notifications_guard_recipient_snapshot()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.user_id IS NOT DISTINCT FROM OLD.user_id
       AND NEW.recipient_principal_kind IS NOT DISTINCT FROM OLD.recipient_principal_kind
       AND NEW.recipient_principal_id IS NOT DISTINCT FROM OLD.recipient_principal_id
       AND NEW.attribution_status IS NOT DISTINCT FROM OLD.attribution_status THEN
        RETURN NEW;
    END IF;

    -- The reviewed management command may classify only a quarantined legacy
    -- row. Every pre-existing event/preference field must remain unchanged.
    IF current_setting('starforge.notification_maintenance', true) = 'principal-backfill'
       AND OLD.attribution_status IN ('unresolved', 'conflicting', 'quarantined')
       AND (
            (
                NEW.attribution_status = 'resolved'
                AND NEW.recipient_principal_kind IN ('student', 'teacher', 'parent', 'staff')
                AND NEW.recipient_principal_id IS NOT NULL
            )
            OR
            (
                NEW.attribution_status IN ('unresolved', 'conflicting', 'quarantined')
                AND NEW.recipient_principal_kind IS NULL
                AND NEW.recipient_principal_id IS NULL
            )
       )
       AND (((to_jsonb(NEW) - 'recipient_principal_kind') - 'recipient_principal_id') - 'attribution_status')
           = (((to_jsonb(OLD) - 'recipient_principal_kind') - 'recipient_principal_id') - 'attribution_status') THEN
        RETURN NEW;
    END IF;

    RAISE EXCEPTION 'notification recipient attribution is immutable'
        USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION notifications_validate_recipient_snapshot()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    recipient_is_live boolean := false;
BEGIN
    IF NEW.attribution_status NOT IN ('captured', 'resolved') THEN
        RETURN NEW;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM users_user recipient_user
         WHERE recipient_user.id = NEW.user_id
           AND recipient_user.is_active
    ) THEN
        RAISE EXCEPTION 'notification recipient principal is not active or owned by user'
            USING ERRCODE = '23514';
    END IF;

    CASE NEW.recipient_principal_kind
        WHEN 'student' THEN
            SELECT EXISTS (
                SELECT 1 FROM students_studentprofile
                 WHERE id = NEW.recipient_principal_id
                   AND user_id = NEW.user_id
                   AND is_active
            ) INTO recipient_is_live;
        WHEN 'teacher' THEN
            SELECT EXISTS (
                SELECT 1 FROM teachers_teacherprofile
                 WHERE id = NEW.recipient_principal_id
                   AND user_id = NEW.user_id
                   AND is_active
            ) INTO recipient_is_live;
        WHEN 'parent' THEN
            SELECT EXISTS (
                SELECT 1 FROM parents_parentprofile
                 WHERE id = NEW.recipient_principal_id
                   AND user_id = NEW.user_id
                   AND is_active
            ) INTO recipient_is_live;
        WHEN 'staff' THEN
            SELECT EXISTS (
                SELECT 1 FROM org_staffprofile
                 WHERE id = NEW.recipient_principal_id
                   AND user_id = NEW.user_id
                   AND is_active
            ) INTO recipient_is_live;
        ELSE
            recipient_is_live := false;
    END CASE;

    IF NOT recipient_is_live THEN
        RAISE EXCEPTION 'notification recipient principal is not active or owned by user'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_recipient_snapshot_immutable ON notifications_notification;
CREATE TRIGGER notification_recipient_snapshot_immutable
BEFORE UPDATE ON notifications_notification
FOR EACH ROW EXECUTE FUNCTION notifications_guard_recipient_snapshot();

DROP TRIGGER IF EXISTS notification_pref_recipient_immutable ON notifications_notificationpreference;
CREATE TRIGGER notification_pref_recipient_immutable
BEFORE UPDATE ON notifications_notificationpreference
FOR EACH ROW EXECUTE FUNCTION notifications_guard_recipient_snapshot();

DROP TRIGGER IF EXISTS notification_recipient_snapshot_valid_insert ON notifications_notification;
CREATE TRIGGER notification_recipient_snapshot_valid_insert
BEFORE INSERT ON notifications_notification
FOR EACH ROW EXECUTE FUNCTION notifications_validate_recipient_snapshot();

DROP TRIGGER IF EXISTS notification_recipient_snapshot_valid_update ON notifications_notification;
CREATE TRIGGER notification_recipient_snapshot_valid_update
BEFORE UPDATE OF user_id, recipient_principal_kind, recipient_principal_id, attribution_status
ON notifications_notification
FOR EACH ROW EXECUTE FUNCTION notifications_validate_recipient_snapshot();

DROP TRIGGER IF EXISTS notification_pref_recipient_valid_insert ON notifications_notificationpreference;
CREATE TRIGGER notification_pref_recipient_valid_insert
BEFORE INSERT ON notifications_notificationpreference
FOR EACH ROW EXECUTE FUNCTION notifications_validate_recipient_snapshot();

DROP TRIGGER IF EXISTS notification_pref_recipient_valid_update ON notifications_notificationpreference;
CREATE TRIGGER notification_pref_recipient_valid_update
BEFORE UPDATE OF user_id, recipient_principal_kind, recipient_principal_id, attribution_status
ON notifications_notificationpreference
FOR EACH ROW EXECUTE FUNCTION notifications_validate_recipient_snapshot();

CREATE OR REPLACE FUNCTION notifications_reject_quarantined_delivery()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM notifications_notification notification
        JOIN users_user recipient_user ON recipient_user.id = notification.user_id
        WHERE notification.id = NEW.notification_id
          AND recipient_user.is_active
          AND notification.attribution_status IN ('captured', 'resolved')
          AND notification.recipient_principal_kind IN ('student', 'teacher', 'parent', 'staff')
          AND notification.recipient_principal_id IS NOT NULL
          AND (
              (
                  notification.recipient_principal_kind = 'student'
                  AND EXISTS (
                      SELECT 1 FROM students_studentprofile principal
                       WHERE principal.id = notification.recipient_principal_id
                         AND principal.user_id = notification.user_id
                         AND principal.is_active
                  )
              )
              OR
              (
                  notification.recipient_principal_kind = 'teacher'
                  AND EXISTS (
                      SELECT 1 FROM teachers_teacherprofile principal
                       WHERE principal.id = notification.recipient_principal_id
                         AND principal.user_id = notification.user_id
                         AND principal.is_active
                  )
              )
              OR
              (
                  notification.recipient_principal_kind = 'parent'
                  AND EXISTS (
                      SELECT 1 FROM parents_parentprofile principal
                       WHERE principal.id = notification.recipient_principal_id
                         AND principal.user_id = notification.user_id
                         AND principal.is_active
                  )
              )
              OR
              (
                  notification.recipient_principal_kind = 'staff'
                  AND EXISTS (
                      SELECT 1 FROM org_staffprofile principal
                       WHERE principal.id = notification.recipient_principal_id
                         AND principal.user_id = notification.user_id
                         AND principal.is_active
                  )
              )
          )
    ) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'cannot deliver a quarantined notification'
        USING ERRCODE = '23514';
END;
$$;

DROP TRIGGER IF EXISTS notification_delivery_requires_principal ON notifications_notificationdelivery;
CREATE TRIGGER notification_delivery_requires_principal
BEFORE INSERT ON notifications_notificationdelivery
FOR EACH ROW EXECUTE FUNCTION notifications_reject_quarantined_delivery();
"""


DROP_RECIPIENT_GUARDS_SQL = r"""
DROP TRIGGER IF EXISTS notification_delivery_requires_principal ON notifications_notificationdelivery;
DROP FUNCTION IF EXISTS notifications_reject_quarantined_delivery();
DROP TRIGGER IF EXISTS notification_pref_recipient_valid_update ON notifications_notificationpreference;
DROP TRIGGER IF EXISTS notification_pref_recipient_valid_insert ON notifications_notificationpreference;
DROP TRIGGER IF EXISTS notification_recipient_snapshot_valid_update ON notifications_notification;
DROP TRIGGER IF EXISTS notification_recipient_snapshot_valid_insert ON notifications_notification;
DROP FUNCTION IF EXISTS notifications_validate_recipient_snapshot();
DROP TRIGGER IF EXISTS notification_pref_recipient_immutable ON notifications_notificationpreference;
DROP TRIGGER IF EXISTS notification_recipient_snapshot_immutable ON notifications_notification;
DROP FUNCTION IF EXISTS notifications_guard_recipient_snapshot();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_alter_notificationdelivery_status"),
        # The guard functions below query every role-native profile table.
        # Depend on the finalized identity-history migrations, not merely the
        # migrations that first create each table: the SQL reads ``is_active``
        # and must not be scheduled before those columns exist on a fresh
        # tenant. ``org.0021`` also brings in the finalized staff profile.
        ("org", "0021_durable_center_settings"),
        ("parents", "0010_preserve_family_lifecycle_history"),
        ("students", "0011_protect_identity_history"),
        ("teachers", "0010_alter_payoutpolicy_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="notif_pref_unique_user_event_channel",
        ),
        migrations.AddField(
            model_name="notification",
            name="attribution_status",
            field=models.CharField(
                choices=[
                    ("captured", "Captured at write time"),
                    ("resolved", "Resolved by reviewed backfill"),
                    ("unresolved", "Unresolved"),
                    ("conflicting", "Conflicting evidence"),
                    ("quarantined", "Quarantined for review"),
                ],
                db_default="unresolved",
                default="unresolved",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_principal_id",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient_principal_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("staff", "Staff"),
                ],
                editable=False,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="attribution_status",
            field=models.CharField(
                choices=[
                    ("captured", "Captured at write time"),
                    ("resolved", "Resolved by reviewed backfill"),
                    ("unresolved", "Unresolved"),
                    ("conflicting", "Conflicting evidence"),
                    ("quarantined", "Quarantined for review"),
                ],
                db_default="unresolved",
                default="unresolved",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="recipient_principal_id",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="recipient_principal_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("staff", "Staff"),
                ],
                editable=False,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "recipient_principal_kind", "recipient_principal_id", "read_at"],
                name="notif_principal_unread_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=[
                    "user",
                    "recipient_principal_kind",
                    "recipient_principal_id",
                    "-created_at",
                    "-id",
                ],
                name="notif_principal_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["attribution_status", "-created_at", "-id"],
                name="notif_attribution_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=[
                    "user",
                    "recipient_principal_kind",
                    "recipient_principal_id",
                    "event_type",
                ],
                name="notif_pref_principal_event_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attribution_status__in", ("captured", "resolved")),
                        ("recipient_principal_id__isnull", False),
                        ("recipient_principal_kind__in", ["student", "teacher", "parent", "staff"]),
                    ),
                    models.Q(
                        ("attribution_status__in", ("unresolved", "conflicting", "quarantined")),
                        ("recipient_principal_id__isnull", True),
                        ("recipient_principal_kind__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="notif_recipient_attribution_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("attribution_status__in", ("captured", "resolved")),
                    ("dedupe_key__isnull", False),
                ),
                fields=("recipient_principal_kind", "recipient_principal_id", "dedupe_key"),
                name="notif_principal_dedupe_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("attribution_status__in", ("unresolved", "conflicting", "quarantined")),
                    ("dedupe_key__isnull", False),
                ),
                fields=("user", "dedupe_key"),
                name="notif_quarantine_dedupe_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attribution_status__in", ("captured", "resolved"))),
                fields=(
                    "recipient_principal_kind",
                    "recipient_principal_id",
                    "event_type",
                    "channel",
                ),
                name="notif_pref_principal_event_channel_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attribution_status__in", ("unresolved", "conflicting", "quarantined"))),
                fields=("user", "event_type", "channel"),
                name="notif_pref_quarantine_event_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("attribution_status__in", ("captured", "resolved")),
                        ("recipient_principal_id__isnull", False),
                        ("recipient_principal_kind__in", ["student", "teacher", "parent", "staff"]),
                    ),
                    models.Q(
                        ("attribution_status__in", ("unresolved", "conflicting", "quarantined")),
                        ("recipient_principal_id__isnull", True),
                        ("recipient_principal_kind__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="notif_pref_attribution_shape",
            ),
        ),
        migrations.RunSQL(RECIPIENT_GUARDS_SQL, DROP_RECIPIENT_GUARDS_SQL),
    ]
