# Generated by Django 6.0.7 on 2026-08-12 20:10

from django.db import migrations, models


_TEMPLATES = {
    'uz': (
        'Sizga yangi vazifa berildi',
        '$creator_name sizga “$task_title” vazifasini berdi. Muddat: $due_at',
    ),
    'ru': (
        'Вам назначена новая задача',
        '$creator_name назначил(а) вам задачу «$task_title». Срок: $due_at',
    ),
    'en': (
        'A new task was assigned to you',
        '$creator_name assigned you “$task_title”. Due: $due_at',
    ),
}


def seed_task_templates(apps, schema_editor):
    template = apps.get_model('notifications', 'NotificationTemplate')
    for channel in ('in_app', 'push', 'email', 'sms'):
        for locale, (subject, body) in _TEMPLATES.items():
            template.objects.update_or_create(
                event_type='task.assigned',
                channel=channel,
                locale=locale,
                defaults={'subject': subject, 'body': body, 'is_active': True},
            )


def unseed_task_templates(apps, schema_editor):
    template = apps.get_model('notifications', 'NotificationTemplate')
    template.objects.filter(event_type='task.assigned').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_cycle_exam_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('task.assigned', 'Task assigned'), ('schedule.lesson_reminder', 'Lesson reminder'), ('schedule.cycle_exam_reminder', 'Cycle exam reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed'), ('message.received', 'Message received'), ('report.ready', 'Report ready'), ('cover.requested', 'Cover requested'), ('cover.approved', 'Cover approved'), ('cover.pool_opened', 'Cover pool opened'), ('cover.rejected', 'Cover rejected')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('task.assigned', 'Task assigned'), ('schedule.lesson_reminder', 'Lesson reminder'), ('schedule.cycle_exam_reminder', 'Cycle exam reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed'), ('message.received', 'Message received'), ('report.ready', 'Report ready'), ('cover.requested', 'Cover requested'), ('cover.approved', 'Cover approved'), ('cover.pool_opened', 'Cover pool opened'), ('cover.rejected', 'Cover rejected')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('attendance.absent', 'Attendance: absent'), ('attendance.late', 'Attendance: late'), ('academics.grades_published', 'Academics: grades published'), ('assignments.created', 'Assignment created'), ('assignments.due_soon', 'Assignment due soon'), ('assignments.graded', 'Assignment graded'), ('task.assigned', 'Task assigned'), ('schedule.lesson_reminder', 'Lesson reminder'), ('schedule.cycle_exam_reminder', 'Cycle exam reminder'), ('auth.new_device_login', 'New device login'), ('students.enrollment_changed', 'Enrollment changed'), ('finance.invoice_issued', 'Invoice issued'), ('finance.payment_reminder', 'Payment reminder'), ('payments.payment_completed', 'Payment completed'), ('payments.payment_failed', 'Payment failed'), ('cohorts.announcement', 'Cohort announcement'), ('billing.subscription_past_due', 'Subscription past due'), ('billing.subscription_suspended', 'Subscription suspended'), ('print.failed', 'Print job failed'), ('approval.approved', 'Request approved'), ('approval.rejected', 'Request rejected'), ('approval.awaiting_disbursement', 'Approved — awaiting disbursement'), ('approval.disbursed', 'Request disbursed'), ('penalty.escalated', 'Penalty: escalation threshold crossed'), ('message.received', 'Message received'), ('report.ready', 'Report ready'), ('cover.requested', 'Cover requested'), ('cover.approved', 'Cover approved'), ('cover.pool_opened', 'Cover pool opened'), ('cover.rejected', 'Cover rejected')], db_index=True, max_length=64),
        ),
        migrations.RunPython(seed_task_templates, unseed_task_templates),
    ]
